// @generated by swarm-engine idl v1.0.0
// world hash: 77a2eae242afd52195fdf7d23649a63d4b73985bb28babe710f0679915d30854
// engine version: 0.1.0
// DO NOT EDIT — this file is auto-generated.


export type UInt32 = number;
export type UInt64 = number | bigint;
export type PlayerId = UInt32;
export type RoomId = UInt32;
export type ObjectId = UInt64;
export type Tick = UInt64;
export type ResourceName = string;
export type ResourceAmount = UInt32;
export type ResourceCost = Record<ResourceName, ResourceAmount>;

export interface Position {
  x: number;
  y: number;
  room: RoomId;
}

export type Direction = "Top" | "TopRight" | "BottomRight" | "Bottom" | "BottomLeft" | "TopLeft";

export type BodyPart = "Move" | "Work" | "Carry" | "Attack" | "RangedAttack" | "Heal" | "Claim" | "Tough";

export type DamageType = "Kinetic" | "Thermal" | "EMP" | "Sonic" | "Corrosive" | "Psionic";

export type RejectionReasonCode = "InvalidJson" | "SchemaViolation" | "ObjectNotFound" | "NotOwner" | "InsufficientResource" | "OutOfRange" | "NotStructure" | "NotController"
  | "NotVisibleOrNotFound" | "TargetNotVisible" | "SpawnOnCooldown" | "RoomDroneCapReached" | "AuthContextInvalid" | "CooldownActive" | "InvalidDirection" | "PositionOccupied"
  | "ConstructionLimitReached" | "SafeModeActive" | "TargetOverloadCooldown" | "TargetFortifyCooldown" | "NotEnoughBodyParts" | "InvalidBodyPart" | "InvalidStructureType" | "InvalidResourceType"
  | "SourceNotAllowed" | "UnknownAction" | "GlobalStorageDisabled" | "TransferInProgress" | "RateLimited" | "InvalidCertificate" | "NotAuthorized" | "FuelExhausted"
  | "TimeoutExceeded" | "SnapshotOverBudget" | "CommandBufferFull" | "ServerOverloaded" | "InternalError";

export type StructureType = "Spawn"
  | "Extension"
  | "Tower"
  | "Storage"
  | "Link"
  | "Extractor"
  | "Lab"
  | "Terminal"
  | "Nuker"
  | "Observer"
  | "PowerSpawn"
  | "Factory"
  | "Depot";

export interface MoveAction {
  type: "Move";
  object_id: ObjectId;
  direction: Direction;
}

export interface HarvestAction {
  type: "Harvest";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
}

export interface TransferAction {
  type: "Transfer";
  object_id: ObjectId;
  target_id: ObjectId;
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface WithdrawAction {
  type: "Withdraw";
  object_id: ObjectId;
  target_id: ObjectId;
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface ClaimControllerAction {
  type: "ClaimController";
  object_id: ObjectId;
  target_id: ObjectId;
}

export interface SpawnAction {
  type: "Spawn";
  object_id: ObjectId;
  spawn_id: ObjectId;
  body_parts: BodyPart[];
}

export interface RecycleAction {
  type: "Recycle";
  object_id: ObjectId;
}

export interface BuildAction {
  type: "Build";
  object_id: ObjectId;
  x: number;
  y: number;
  structure: StructureType;
}

export interface RepairAction {
  type: "Repair";
  object_id: ObjectId;
  target_id: ObjectId;
}

export interface UpgradeControllerAction {
  type: "UpgradeController";
  object_id: ObjectId;
  target_id: ObjectId;
}

export interface TransferToGlobalAction {
  type: "TransferToGlobal";
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface TransferFromGlobalAction {
  type: "TransferFromGlobal";
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface AlliedTransferAction {
  type: "AlliedTransfer";
  target_player: PlayerId;
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface CreateContractSettlementAction {
  type: "CreateContractSettlement";
  settlement_id: UInt64;
  nonce: UInt64;
  input_resource: ResourceName;
  input_amount: ResourceAmount;
  output_resource: ResourceName;
  output_amount: ResourceAmount;
  counterparty?: PlayerId;
  expires_at?: UInt64;
}

export interface SettleContractAction {
  type: "SettleContract";
  settlement_id: UInt64;
}

export interface CancelContractAction {
  type: "CancelContract";
  settlement_id: UInt64;
}

export interface CreateMerchantQuoteAction {
  type: "CreateMerchantQuote";
  quote_id: UInt64;
  player_id: PlayerId;
  pay_resource: ResourceName;
  pay_amount: ResourceAmount;
  receive_resource: ResourceName;
  receive_amount: ResourceAmount;
  expires_at: UInt64;
}

export interface AcceptMerchantTradeAction {
  type: "AcceptMerchantTrade";
  quote_id: UInt64;
  min_receive: ResourceAmount;
}

export interface CreateP2POfferAction {
  type: "CreateP2POffer";
  offer_id: UInt64;
  nonce: UInt64;
  give_resource: ResourceName;
  give_amount: ResourceAmount;
  want_resource: ResourceName;
  want_amount: ResourceAmount;
  expires_at: UInt64;
}

export interface AcceptP2POfferAction {
  type: "AcceptP2POffer";
  offer_id: UInt64;
}

export interface CancelP2POfferAction {
  type: "CancelP2POffer";
  offer_id: UInt64;
}

export interface RefundP2POfferAction {
  type: "RefundP2POffer";
  offer_id: UInt64;
}

export interface CreateAuctionAction {
  type: "CreateAuction";
  auction_id: UInt64;
  nonce: UInt64;
  lot_resource: ResourceName;
  lot_amount: ResourceAmount;
  bid_resource: ResourceName;
  min_bid: ResourceAmount;
  ends_at: UInt64;
}

export interface BidAuctionAction {
  type: "BidAuction";
  auction_id: UInt64;
  bid_amount: ResourceAmount;
}

export interface SettleAuctionAction {
  type: "SettleAuction";
  auction_id: UInt64;
}

export interface CancelAuctionAction {
  type: "CancelAuction";
  auction_id: UInt64;
}

export interface CreateEscrowAction {
  type: "CreateEscrow";
  escrow_id: UInt64;
  nonce: UInt64;
  payee: PlayerId;
  arbiter: PlayerId;
  resource: ResourceName;
  amount: ResourceAmount;
}

export interface ReleaseEscrowAction {
  type: "ReleaseEscrow";
  escrow_id: UInt64;
}

export interface RefundEscrowAction {
  type: "RefundEscrow";
  escrow_id: UInt64;
}

export interface CreateLoanOfferAction {
  type: "CreateLoanOffer";
  loan_id: UInt64;
  nonce: UInt64;
  borrower: PlayerId;
  resource: ResourceName;
  principal: ResourceAmount;
  repay_amount: ResourceAmount;
  due_at: UInt64;
}

export interface AcceptLoanAction {
  type: "AcceptLoan";
  loan_id: UInt64;
}

export interface RepayLoanAction {
  type: "RepayLoan";
  loan_id: UInt64;
}

export interface DefaultLoanAction {
  type: "DefaultLoan";
  loan_id: UInt64;
}


// ── Built-in ActionRegistry wire actions ──

export interface AttackAction {
  type: "Attack";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface RangedAttackAction {
  type: "RangedAttack";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface HealAction {
  type: "Heal";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface HackAction {
  type: "Hack";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface DrainAction {
  type: "Drain";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface OverloadAction {
  type: "Overload";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface DebilitateAction {
  type: "Debilitate";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface DisruptAction {
  type: "Disrupt";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface FortifyAction {
  type: "Fortify";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface LeechAction {
  type: "Leech";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export interface FabricateAction {
  type: "Fabricate";
  object_id: ObjectId;
  target_id: ObjectId;
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}


// ── Custom actions (from world.toml mods) ──


export type Action = MoveAction
  | HarvestAction
  | TransferAction
  | WithdrawAction
  | ClaimControllerAction
  | SpawnAction
  | RecycleAction
  | BuildAction
  | RepairAction
  | UpgradeControllerAction
  | TransferToGlobalAction
  | TransferFromGlobalAction
  | AlliedTransferAction
  | CreateContractSettlementAction
  | SettleContractAction
  | CancelContractAction
  | CreateMerchantQuoteAction
  | AcceptMerchantTradeAction
  | CreateP2POfferAction
  | AcceptP2POfferAction
  | CancelP2POfferAction
  | RefundP2POfferAction
  | CreateAuctionAction
  | BidAuctionAction
  | SettleAuctionAction
  | CancelAuctionAction
  | CreateEscrowAction
  | ReleaseEscrowAction
  | RefundEscrowAction
  | CreateLoanOfferAction
  | AcceptLoanAction
  | RepayLoanAction
  | DefaultLoanAction
  | AttackAction
  | RangedAttackAction
  | HealAction
  | HackAction
  | DrainAction
  | OverloadAction
  | DebilitateAction
  | DisruptAction
  | FortifyAction
  | LeechAction
  | FabricateAction;


export interface CommandIntent<A extends Action = Action> {
  sequence: UInt32;
  action: A;
}

export interface SpecialActionPayload {
  resource?: ResourceName;
  amount?: ResourceAmount;
  range?: number;
  structure?: StructureType;
  damage_type?: DamageType;
  cooldown?: number;
}

export function addCost(target: ResourceCost, source: ResourceCost): ResourceCost {
  for (const [res, amt] of Object.entries(source)) {
    target[res] = (target[res] ?? 0) + amt;
  }
  return target;
}

export function command<A extends Action>(sequence: number, action: A): CommandIntent<A> {
  return { sequence, action };
}

export const actions = Object.freeze({
  move: (object_id: ObjectId, direction: Direction) => ({ type: "Move", object_id, direction }) as const,
  harvest: (object_id: ObjectId, target_id: ObjectId, resource?: ResourceName) => ({ type: "Harvest", object_id, target_id, resource }) as const,
  transfer: (object_id: ObjectId, target_id: ObjectId, resource: ResourceName, amount: ResourceAmount) => ({ type: "Transfer", object_id, target_id, resource, amount }) as const,
  withdraw: (object_id: ObjectId, target_id: ObjectId, resource: ResourceName, amount: ResourceAmount) => ({ type: "Withdraw", object_id, target_id, resource, amount }) as const,
  claimController: (object_id: ObjectId, target_id: ObjectId) => ({ type: "ClaimController", object_id, target_id }) as const,
  spawn: (object_id: ObjectId, spawn_id: ObjectId, body_parts: BodyPart[]) => ({ type: "Spawn", object_id, spawn_id, body_parts }) as const,
  recycle: (object_id: ObjectId) => ({ type: "Recycle", object_id }) as const,
  build: (object_id: ObjectId, x: number, y: number, structure: StructureType) => ({ type: "Build", object_id, x, y, structure }) as const,
  repair: (object_id: ObjectId, target_id: ObjectId) => ({ type: "Repair", object_id, target_id }) as const,
  upgradeController: (object_id: ObjectId, target_id: ObjectId) => ({ type: "UpgradeController", object_id, target_id }) as const,
  transferToGlobal: (resource: ResourceName, amount: ResourceAmount) => ({ type: "TransferToGlobal", resource, amount }) as const,
  transferFromGlobal: (resource: ResourceName, amount: ResourceAmount) => ({ type: "TransferFromGlobal", resource, amount }) as const,
  alliedTransfer: (target_player: PlayerId, resource: ResourceName, amount: ResourceAmount) => ({ type: "AlliedTransfer", target_player, resource, amount }) as const,
  createContractSettlement: (settlement_id: UInt64, nonce: UInt64, input_resource: ResourceName, input_amount: ResourceAmount, output_resource: ResourceName, output_amount: ResourceAmount, counterparty?: PlayerId, expires_at?: UInt64) => ({ type: "CreateContractSettlement", settlement_id, nonce, input_resource, input_amount, output_resource, output_amount, counterparty, expires_at }) as const,
  settleContract: (settlement_id: UInt64) => ({ type: "SettleContract", settlement_id }) as const,
  cancelContract: (settlement_id: UInt64) => ({ type: "CancelContract", settlement_id }) as const,
  createMerchantQuote: (quote_id: UInt64, player_id: PlayerId, pay_resource: ResourceName, pay_amount: ResourceAmount, receive_resource: ResourceName, receive_amount: ResourceAmount, expires_at: UInt64) => ({ type: "CreateMerchantQuote", quote_id, player_id, pay_resource, pay_amount, receive_resource, receive_amount, expires_at }) as const,
  acceptMerchantTrade: (quote_id: UInt64, min_receive: ResourceAmount) => ({ type: "AcceptMerchantTrade", quote_id, min_receive }) as const,
  createP2POffer: (offer_id: UInt64, nonce: UInt64, give_resource: ResourceName, give_amount: ResourceAmount, want_resource: ResourceName, want_amount: ResourceAmount, expires_at: UInt64) => ({ type: "CreateP2POffer", offer_id, nonce, give_resource, give_amount, want_resource, want_amount, expires_at }) as const,
  acceptP2POffer: (offer_id: UInt64) => ({ type: "AcceptP2POffer", offer_id }) as const,
  cancelP2POffer: (offer_id: UInt64) => ({ type: "CancelP2POffer", offer_id }) as const,
  refundP2POffer: (offer_id: UInt64) => ({ type: "RefundP2POffer", offer_id }) as const,
  createAuction: (auction_id: UInt64, nonce: UInt64, lot_resource: ResourceName, lot_amount: ResourceAmount, bid_resource: ResourceName, min_bid: ResourceAmount, ends_at: UInt64) => ({ type: "CreateAuction", auction_id, nonce, lot_resource, lot_amount, bid_resource, min_bid, ends_at }) as const,
  bidAuction: (auction_id: UInt64, bid_amount: ResourceAmount) => ({ type: "BidAuction", auction_id, bid_amount }) as const,
  settleAuction: (auction_id: UInt64) => ({ type: "SettleAuction", auction_id }) as const,
  cancelAuction: (auction_id: UInt64) => ({ type: "CancelAuction", auction_id }) as const,
  createEscrow: (escrow_id: UInt64, nonce: UInt64, payee: PlayerId, arbiter: PlayerId, resource: ResourceName, amount: ResourceAmount) => ({ type: "CreateEscrow", escrow_id, nonce, payee, arbiter, resource, amount }) as const,
  releaseEscrow: (escrow_id: UInt64) => ({ type: "ReleaseEscrow", escrow_id }) as const,
  refundEscrow: (escrow_id: UInt64) => ({ type: "RefundEscrow", escrow_id }) as const,
  createLoanOffer: (loan_id: UInt64, nonce: UInt64, borrower: PlayerId, resource: ResourceName, principal: ResourceAmount, repay_amount: ResourceAmount, due_at: UInt64) => ({ type: "CreateLoanOffer", loan_id, nonce, borrower, resource, principal, repay_amount, due_at }) as const,
  acceptLoan: (loan_id: UInt64) => ({ type: "AcceptLoan", loan_id }) as const,
  repayLoan: (loan_id: UInt64) => ({ type: "RepayLoan", loan_id }) as const,
  defaultLoan: (loan_id: UInt64) => ({ type: "DefaultLoan", loan_id }) as const,
  attack: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Attack", object_id, target_id, ...payload }) as const,
  rangedAttack: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "RangedAttack", object_id, target_id, ...payload }) as const,
  heal: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Heal", object_id, target_id, ...payload }) as const,
  hack: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Hack", object_id, target_id, ...payload }) as const,
  drain: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Drain", object_id, target_id, ...payload }) as const,
  overload: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Overload", object_id, target_id, ...payload }) as const,
  debilitate: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Debilitate", object_id, target_id, ...payload }) as const,
  disrupt: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Disrupt", object_id, target_id, ...payload }) as const,
  fortify: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Fortify", object_id, target_id, ...payload }) as const,
  leech: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Leech", object_id, target_id, ...payload }) as const,
  fabricate: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {}) =>
    ({ type: "Fabricate", object_id, target_id, ...payload }) as const,
});

export const BODY_PART_COST = {
  Attack: { Energy: 80 },
  Carry: { Energy: 50 },
  Claim: { Energy: 600 },
  Heal: { Energy: 250 },
  Move: { Energy: 50 },
  RangedAttack: { Energy: 100 },
  Tough: { Energy: 10 },
  Work: { Energy: 100 }
} as const;

export function bodyCost(body: BodyPart[]): ResourceCost {
  const total: ResourceCost = {};
  for (const part of body) {
    const cost = BODY_PART_COST[part] ?? {};
    for (const [res, amt] of Object.entries(cost)) {
      total[res] = (total[res] ?? 0) + amt;
    }
  }
  return total;
}

export interface RealtimePosition {
  x: number;
  y: number;
  room_id: RoomId;
}

export interface RealtimeVisibleEntity {
  type: "Drone" | "Structure" | "Source" | "Resource" | "Controller";
  id: ObjectId;
  position: RealtimePosition;
  owner?: PlayerId | null;
  structure_type?: string;
  body?: BodyPart[];
  carry?: ResourceCost;
  hits?: UInt32;
  energy?: UInt32 | null;
  produces?: ResourceCost;
  amounts?: ResourceCost;
  level?: UInt32;
}

export interface RealtimePayloadV1 {
  tick: Tick;
  last_tick: Tick;
  player_id: PlayerId;
  full_snapshot: boolean;
  changed_entities: RealtimeVisibleEntity[];
  removed_entities: ObjectId[];
  state_checksum: UInt64;
}

export interface RealtimeEnvelopeV1 {
  schema: "swarm.realtime.v1";
  payload: RealtimePayloadV1;
}


// ── Constants ──

export const SDK_VERSION = "0.1.0";
export const IDL_VERSION = "1.0.0";
export const ABI_VERSION = 1;

export const AI_GAME_DATA_START = "___AI_GAME_DATA_START___";
export const AI_GAME_DATA_END = "___AI_GAME_DATA_END___";

export const MAX_BODY_PARTS = 50;
export const MAX_COMMANDS_PER_PLAYER = 100;
export const MAX_DRONES_PER_PLAYER = 500;
export const MAX_FUEL = 10000000;
export const MAX_JSON_DEPTH = 10;
export const MAX_NEXT_TICK_FUEL_BUDGET = 11000000;
export const MAX_RANGED_ATTACK_RANGE = 3;
export const MAX_REFUND_PER_TICK = 1000000;
export const MAX_TICK_OUTPUT_BYTES = 262144;
