// @generated by swarm-engine idl v1.0.0
// world hash: 77a2eae242afd52195fdf7d23649a63d4b73985bb28babe710f0679915d30854
// engine version: 0.1.0
// DO NOT EDIT — this file is auto-generated.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Direction {
    Top,
    TopRight,
    BottomRight,
    Bottom,
    BottomLeft,
    TopLeft,
}

impl Direction {
    pub const fn offset(self) -> (i32, i32) {
        match self {
            Direction::Top => (0, -1),
            Direction::TopRight => (1, -1),
            Direction::BottomRight => (1, 0),
            Direction::Bottom => (0, 1),
            Direction::BottomLeft => (-1, 1),
            Direction::TopLeft => (-1, 0),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BodyPart {
    Move,
    Work,
    Carry,
    Attack,
    RangedAttack,
    Heal,
    Claim,
    Tough,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DamageType {
    Kinetic,
    Thermal,
    EMP,
    Sonic,
    Corrosive,
    Psionic,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct StructureType(pub &'static str);

impl StructureType {
    pub const SPAWN: Self = Self("Spawn");
    pub const EXTENSION: Self = Self("Extension");
    pub const TOWER: Self = Self("Tower");
    pub const STORAGE: Self = Self("Storage");
    pub const LINK: Self = Self("Link");
    pub const EXTRACTOR: Self = Self("Extractor");
    pub const LAB: Self = Self("Lab");
    pub const TERMINAL: Self = Self("Terminal");
    pub const NUKER: Self = Self("Nuker");
    pub const OBSERVER: Self = Self("Observer");
    pub const POWERSPAWN: Self = Self("PowerSpawn");
    pub const FACTORY: Self = Self("Factory");
    pub const DEPOT: Self = Self("Depot");

    pub fn new(name: impl Into<String>) -> Self {
        Self(Box::leak(name.into().into_boxed_str()))
    }

    pub fn as_str(self) -> &'static str {
        self.0
    }
    #[allow(non_upper_case_globals)]
    pub const Spawn: Self = Self::SPAWN;
    #[allow(non_upper_case_globals)]
    pub const Extension: Self = Self::EXTENSION;
    #[allow(non_upper_case_globals)]
    pub const Tower: Self = Self::TOWER;
    #[allow(non_upper_case_globals)]
    pub const Storage: Self = Self::STORAGE;
    #[allow(non_upper_case_globals)]
    pub const Link: Self = Self::LINK;
    #[allow(non_upper_case_globals)]
    pub const Extractor: Self = Self::EXTRACTOR;
    #[allow(non_upper_case_globals)]
    pub const Lab: Self = Self::LAB;
    #[allow(non_upper_case_globals)]
    pub const Terminal: Self = Self::TERMINAL;
    #[allow(non_upper_case_globals)]
    pub const Nuker: Self = Self::NUKER;
    #[allow(non_upper_case_globals)]
    pub const Observer: Self = Self::OBSERVER;
    #[allow(non_upper_case_globals)]
    pub const PowerSpawn: Self = Self::POWERSPAWN;
    #[allow(non_upper_case_globals)]
    pub const Factory: Self = Self::FACTORY;
    #[allow(non_upper_case_globals)]
    pub const Depot: Self = Self::DEPOT;
}

impl Serialize for StructureType {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.0)
    }
}

impl<'de> Deserialize<'de> for StructureType {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        String::deserialize(d).map(Self::new)
    }
}

impl std::fmt::Display for StructureType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

impl Default for StructureType {
    fn default() -> Self {
        Self::SPAWN
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", deny_unknown_fields)]
pub enum CommandAction {
    Move {
        object_id: u64,
        direction: Direction,
    },
    Harvest {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
    },
    Transfer {
        object_id: u64,
        target_id: u64,
        resource: String,
        amount: u32,
    },
    Withdraw {
        object_id: u64,
        target_id: u64,
        resource: String,
        amount: u32,
    },
    ClaimController {
        object_id: u64,
        target_id: u64,
    },
    Spawn {
        object_id: u64,
        spawn_id: u64,
        body_parts: Vec<BodyPart>,
    },
    Recycle {
        object_id: u64,
    },
    Build {
        object_id: u64,
        x: i32,
        y: i32,
        structure: StructureType,
    },
    Repair {
        object_id: u64,
        target_id: u64,
    },
    UpgradeController {
        object_id: u64,
        target_id: u64,
    },
    TransferToGlobal {
        resource: String,
        amount: u32,
    },
    TransferFromGlobal {
        resource: String,
        amount: u32,
    },
    AlliedTransfer {
        target_player: u32,
        resource: String,
        amount: u32,
    },
    Attack {
        object_id: u64,
        target_id: u64,
    },
    RangedAttack {
        object_id: u64,
        target_id: u64,
    },
    Heal {
        object_id: u64,
        target_id: u64,
    },
    Hack {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Drain {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Overload {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Debilitate {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Disrupt {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Fortify {
        object_id: u64,
        target_id: u64,
        cooldown: Option<u32>,
    },
    Leech {
        object_id: u64,
        target_id: u64,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Fabricate {
        object_id: u64,
        target_id: u64,
        cooldown: Option<u32>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Command {
    pub sequence: u32,
    pub action: CommandAction,
}

// ── Custom action constructors (方案β: typed helpers) ──

impl CommandAction {
    /// Melee attack target
    pub fn attack(object_id: u64, target_id: u64) -> Self {
        CommandAction::Attack {
            object_id,
            target_id,
        }
    }

    /// Ranged attack target
    pub fn rangedattack(object_id: u64, target_id: u64) -> Self {
        CommandAction::RangedAttack {
            object_id,
            target_id,
        }
    }

    /// Repair or heal target
    pub fn heal(object_id: u64, target_id: u64) -> Self {
        CommandAction::Heal {
            object_id,
            target_id,
        }
    }

    /// 5-stage intrusion attack
    pub fn hack(object_id: u64, target_id: u64) -> Self {
        CommandAction::Hack {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Continuously drain resources from target
    pub fn drain(object_id: u64, target_id: u64) -> Self {
        CommandAction::Drain {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Reduce target player fuel budget
    pub fn overload(object_id: u64, target_id: u64) -> Self {
        CommandAction::Overload {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Apply vulnerability to a target damage type for 50 ticks
    pub fn debilitate(object_id: u64, target_id: u64) -> Self {
        CommandAction::Debilitate {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Interrupt target current continuous action
    pub fn disrupt(object_id: u64, target_id: u64) -> Self {
        CommandAction::Disrupt {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Shield and cleanse self or an ally
    pub fn fortify(object_id: u64, target_id: u64) -> Self {
        CommandAction::Fortify {
            object_id,
            target_id,
            cooldown: None,
        }
    }

    /// Kinetic attack that heals the attacker for 50% of dealt damage
    pub fn leech(object_id: u64, target_id: u64) -> Self {
        CommandAction::Leech {
            object_id,
            target_id,
            damage_type: None,
            cooldown: None,
        }
    }

    /// Convert enemy drone into an owned structure
    pub fn fabricate(object_id: u64, target_id: u64) -> Self {
        CommandAction::Fabricate {
            object_id,
            target_id,
            cooldown: None,
        }
    }
}

// ── Constants ──

pub const MAX_BODY_PARTS: u64 = 50;
pub const MAX_COMMANDS_PER_PLAYER: u64 = 100;
pub const MAX_DRONES_PER_PLAYER: u64 = 500;
pub const MAX_FUEL: u64 = 10000000;
pub const MAX_JSON_DEPTH: u64 = 10;
pub const MAX_NEXT_TICK_FUEL_BUDGET: u64 = 11000000;
pub const MAX_RANGED_ATTACK_RANGE: u64 = 3;
pub const MAX_REFUND_PER_TICK: u64 = 1000000;
pub const MAX_TICK_OUTPUT_BYTES: u64 = 262144;

pub const BODY_PART_COST: &[(BodyPart, u32)] = &[
    (BodyPart::Attack, 80),
    (BodyPart::Carry, 50),
    (BodyPart::Claim, 600),
    (BodyPart::Heal, 250),
    (BodyPart::Move, 50),
    (BodyPart::RangedAttack, 100),
    (BodyPart::Tough, 10),
    (BodyPart::Work, 100),
];

pub fn body_energy_cost(body: &[BodyPart]) -> u32 {
    body.iter()
        .filter_map(|part| {
            BODY_PART_COST
                .iter()
                .find(|(p, _)| p == part)
                .map(|(_, cost)| *cost)
        })
        .sum()
}
