// @generated by swarm-engine idl v1.0.0
// world hash: 0b4b0be62e3535e1b7b6ef1467249cd53eb0557e5e0a08b585abecb753edb625
// engine version: 0.1.0
// DO NOT EDIT — this file is auto-generated.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Direction {
    Top,
    TopRight,
    BottomRight,
    Bottom,
    BottomLeft,
    TopLeft,
}

impl Direction {
    pub const fn offset(self) -> (i32, i32) {
        match self {
            Direction::Top => (0, -1),
            Direction::TopRight => (1, -1),
            Direction::BottomRight => (1, 0),
            Direction::Bottom => (0, 1),
            Direction::BottomLeft => (-1, 1),
            Direction::TopLeft => (-1, 0),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum BodyPart {
    Move,
    Work,
    Carry,
    Attack,
    RangedAttack,
    Heal,
    Claim,
    Tough,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DamageType {
    Kinetic,
    Thermal,
    EMP,
    Sonic,
    Corrosive,
    Psionic,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct StructureType(pub &'static str);

impl StructureType {
    pub const SPAWN: Self = Self("Spawn");
    pub const EXTENSION: Self = Self("Extension");
    pub const TOWER: Self = Self("Tower");
    pub const STORAGE: Self = Self("Storage");
    pub const LINK: Self = Self("Link");
    pub const EXTRACTOR: Self = Self("Extractor");
    pub const LAB: Self = Self("Lab");
    pub const TERMINAL: Self = Self("Terminal");
    pub const NUKER: Self = Self("Nuker");
    pub const OBSERVER: Self = Self("Observer");
    pub const POWERSPAWN: Self = Self("PowerSpawn");
    pub const FACTORY: Self = Self("Factory");
    pub const DEPOT: Self = Self("Depot");

    pub fn new(name: impl Into<String>) -> Self {
        Self(Box::leak(name.into().into_boxed_str()))
    }

    pub fn as_str(self) -> &'static str {
        self.0
    }
    #[allow(non_upper_case_globals)]
    pub const Spawn: Self = Self::SPAWN;
    #[allow(non_upper_case_globals)]
    pub const Extension: Self = Self::EXTENSION;
    #[allow(non_upper_case_globals)]
    pub const Tower: Self = Self::TOWER;
    #[allow(non_upper_case_globals)]
    pub const Storage: Self = Self::STORAGE;
    #[allow(non_upper_case_globals)]
    pub const Link: Self = Self::LINK;
    #[allow(non_upper_case_globals)]
    pub const Extractor: Self = Self::EXTRACTOR;
    #[allow(non_upper_case_globals)]
    pub const Lab: Self = Self::LAB;
    #[allow(non_upper_case_globals)]
    pub const Terminal: Self = Self::TERMINAL;
    #[allow(non_upper_case_globals)]
    pub const Nuker: Self = Self::NUKER;
    #[allow(non_upper_case_globals)]
    pub const Observer: Self = Self::OBSERVER;
    #[allow(non_upper_case_globals)]
    pub const PowerSpawn: Self = Self::POWERSPAWN;
    #[allow(non_upper_case_globals)]
    pub const Factory: Self = Self::FACTORY;
    #[allow(non_upper_case_globals)]
    pub const Depot: Self = Self::DEPOT;
}

impl Serialize for StructureType {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        s.serialize_str(self.0)
    }
}

impl<'de> Deserialize<'de> for StructureType {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        String::deserialize(d).map(Self::new)
    }
}

impl std::fmt::Display for StructureType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.0)
    }
}

impl Default for StructureType {
    fn default() -> Self {
        Self::SPAWN
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", deny_unknown_fields)]
pub enum CommandAction {
    Move {
        object_id: u64,
        direction: Direction,
    },
    Harvest {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
    },
    Transfer {
        object_id: u64,
        target_id: u64,
        resource: String,
        amount: u32,
    },
    Withdraw {
        object_id: u64,
        target_id: u64,
        resource: String,
        amount: u32,
    },
    ClaimController {
        object_id: u64,
        target_id: u64,
    },
    Spawn {
        object_id: u64,
        spawn_id: u64,
        body_parts: Vec<BodyPart>,
    },
    Recycle {
        object_id: u64,
    },
    Build {
        object_id: u64,
        x: i32,
        y: i32,
        structure: StructureType,
    },
    Repair {
        object_id: u64,
        target_id: u64,
    },
    UpgradeController {
        object_id: u64,
        target_id: u64,
    },
    TransferToGlobal {
        resource: String,
        amount: u32,
    },
    TransferFromGlobal {
        resource: String,
        amount: u32,
    },
    AlliedTransfer {
        target_player: u32,
        resource: String,
        amount: u32,
    },
    Attack {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    RangedAttack {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Heal {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Hack {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Drain {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Overload {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Debilitate {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Disrupt {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Fortify {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Leech {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
    Fabricate {
        object_id: u64,
        target_id: u64,
        resource: Option<String>,
        amount: Option<u32>,
        range: Option<u32>,
        structure: Option<StructureType>,
        damage_type: Option<DamageType>,
        cooldown: Option<u32>,
    },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandIntent {
    pub sequence: u32,
    pub idempotency_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_trace_id: Option<String>,
    pub action: CommandAction,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TickInput {
    pub tick: u64,
    pub player_id: u32,
    pub world_id: u64,
    pub visible_snapshot: Vec<u8>,
    pub world_config_view: WorldConfigView,
    pub fuel_budget_hints: FuelBudgetHints,
    pub message_inbox_cursor: MessageInboxCursor,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorldConfigView {
    pub config_hash: [u8; 32],
    pub payload: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FuelBudgetHints {
    pub fuel_remaining: u64,
    pub host_calls_remaining: u32,
    pub output_bytes_remaining: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MessageInboxCursor {
    pub next_message_id: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TickResult {
    pub commands: Vec<CommandIntent>,
    #[serde(default)]
    pub messages: Vec<PlayerMessage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlayerMessage {
    pub topic: String,
    pub payload: Vec<u8>,
}

// ── Custom action constructors (方案β: typed helpers) ──

impl CommandAction {}

// ── Constants ──

pub const MAX_BODY_PARTS: u64 = 50;
pub const MAX_COMMANDS_PER_PLAYER: u64 = 100;
pub const MAX_DRONES_PER_PLAYER: u64 = 500;
pub const MAX_FUEL: u64 = 10000000;
pub const MAX_JSON_DEPTH: u64 = 10;
pub const MAX_NEXT_TICK_FUEL_BUDGET: u64 = 11000000;
pub const MAX_RANGED_ATTACK_RANGE: u64 = 3;
pub const MAX_REFUND_PER_TICK: u64 = 1000000;
pub const MAX_TICK_OUTPUT_BYTES: u64 = 262144;

pub const BODY_PART_COST: &[(BodyPart, u32)] = &[
    (BodyPart::Attack, 80),
    (BodyPart::Carry, 50),
    (BodyPart::Claim, 600),
    (BodyPart::Heal, 250),
    (BodyPart::Move, 50),
    (BodyPart::RangedAttack, 100),
    (BodyPart::Tough, 10),
    (BodyPart::Work, 100),
];

pub fn body_energy_cost(body: &[BodyPart]) -> u32 {
    body.iter()
        .filter_map(|part| {
            BODY_PART_COST
                .iter()
                .find(|(p, _)| p == part)
                .map(|(_, cost)| *cost)
        })
        .sum()
}
