// commands.rs — generated by swarm-engine IDL codegen (Direction, BodyPart, CommandAction, constants)
pub mod commands;
// types_template.rs — stable SDK types (Snapshot, ObjectKind, etc.)
pub mod types_template;
pub mod bot;

pub use commands::*;
pub use types_template::*;

pub fn tick(snapshot: Snapshot) -> TickResult {
    bot::tick(snapshot)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // ── Original tests (keep these) ────────────────────────────────────

    #[test]
    fn spawn_serializes_with_spawn_type() {
        let command = Command {
            sequence: 7,
            action: CommandAction::SpawnDrone {
                spawn_id: 42,
                body: vec![BodyPart::Move, BodyPart::Work, BodyPart::Carry],
            },
        };

        let value = serde_json::to_value(command).unwrap();

        assert_eq!(
            value,
            json!({
                "sequence": 7,
                "action": {
                    "type": "Spawn",
                    "spawn_id": 42,
                    "body": ["Move", "Work", "Carry"]
                }
            })
        );
    }

    #[test]
    fn tick_returns_no_commands_without_spawn_and_source() {
        let result = tick(Snapshot {
            tick: 1,
            player_id: 2,
            rooms: vec![],
            objects: vec![],
            player: None,
        });
        assert!(result.commands.is_empty());
    }

    // ── New serialization round-trip tests ─────────────────────────────

    #[test]
    fn command_action_round_trip_all_variants() {
        let cases: Vec<CommandAction> = vec![
            CommandAction::Move {
                object_id: 1,
                direction: Direction::TopRight,
            },
            CommandAction::Harvest {
                object_id: 2,
                target_id: 10,
                resource: Some("Energy".into()),
            },
            CommandAction::Transfer {
                object_id: 3,
                target_id: 11,
                resource: "Energy".into(),
                amount: 100,
            },
            CommandAction::Withdraw {
                object_id: 4,
                target_id: 12,
                resource: "Energy".into(),
                amount: 50,
            },
            CommandAction::Attack {
                object_id: 5,
                target_id: 13,
            },
            CommandAction::Heal {
                object_id: 6,
                target_id: 14,
            },
            CommandAction::Build {
                object_id: 8,
                x: 20,
                y: 30,
                structure: StructureType::Spawn,
            },
            CommandAction::SpawnDrone {
                spawn_id: 9,
                body: vec![BodyPart::Move, BodyPart::Work, BodyPart::Carry],
            },
            CommandAction::TransferToGlobal {
                resource: "Energy".into(),
                amount: 500,
            },
            CommandAction::TransferFromGlobal {
                resource: "Energy".into(),
                amount: 200,
            },
        ];

        for action in &cases {
            let json = serde_json::to_string(action).expect("serialization failed");
            let parsed: CommandAction =
                serde_json::from_str(&json).expect("deserialization failed");
            assert_eq!(
                action, &parsed,
                "round-trip mismatch for {:?}\nJSON: {}",
                action, json
            );
        }
    }

    #[test]
    fn constants_are_correct() {
        assert_eq!(MAX_FUEL, 10_000_000);
        assert_eq!(MAX_COMMANDS_PER_PLAYER, 100);
        assert_eq!(MAX_BODY_PARTS, 50);
        assert!(!BODY_PART_COST.is_empty());
    }

    #[test]
    fn body_energy_cost_sums_correctly() {
        // [Move, Work, Carry] = 50 + 100 + 50 = 200
        assert_eq!(
            body_energy_cost(&[BodyPart::Move, BodyPart::Work, BodyPart::Carry]),
            200
        );
        // Empty body
        assert_eq!(body_energy_cost(&[]), 0);
    }
}
