use std::path::Path;

use schemars::schema_for;
use swarm_engine_api::{abi::CommandIntent, ids::BodyPart};
use ts_rs::{Config as TsConfig, TS};

use crate::command::Direction;
use crate::components::TerrainType;
use crate::mcp::{
    VisibleController, VisibleDrone, VisibleEntity, VisiblePendingGlobalTransfer, VisiblePosition,
    VisibleResource, VisibleSource, VisibleStructure, VisibleTile, VisibleWorldSnapshot,
};
use crate::realtime::{RealtimeDelta, RealtimeEnvelope};

pub fn export_contract_artifacts(out_dir: impl AsRef<Path>) -> Result<(), String> {
    let out_dir = out_dir.as_ref();
    std::fs::create_dir_all(out_dir)
        .map_err(|error| format!("create {}: {error}", out_dir.display()))?;
    let ts = generate_typescript_contracts()?;
    write_if_changed(out_dir.join("swarm-contracts.ts"), &ts)?;
    write_schema(
        out_dir.join("command-intent.schema.json"),
        &schema_for!(Vec<CommandIntent>),
    )?;
    write_schema(
        out_dir.join("realtime.schema.json"),
        &schema_for!(RealtimeEnvelope),
    )?;
    write_schema(
        out_dir.join("visible-snapshot.schema.json"),
        &schema_for!(VisibleWorldSnapshot),
    )?;
    Ok(())
}

pub fn generate_typescript_contracts() -> Result<String, String> {
    let cfg = TsConfig::new().with_large_int("number");
    let mut out = String::from("// @generated by swarm-engine contract export. DO NOT EDIT.\n\n");
    for exported in [
        Direction::export_to_string(&cfg),
        BodyPart::export_to_string(&cfg),
        TerrainType::export_to_string(&cfg),
        VisiblePosition::export_to_string(&cfg),
        VisibleTile::export_to_string(&cfg),
        VisiblePendingGlobalTransfer::export_to_string(&cfg),
        VisibleDrone::export_to_string(&cfg),
        VisibleStructure::export_to_string(&cfg),
        VisibleSource::export_to_string(&cfg),
        VisibleResource::export_to_string(&cfg),
        VisibleController::export_to_string(&cfg),
        VisibleEntity::export_to_string(&cfg),
        RealtimeDelta::export_to_string(&cfg),
        RealtimeEnvelope::export_to_string(&cfg),
        VisibleWorldSnapshot::export_to_string(&cfg),
    ] {
        let exported = exported.map_err(|error| error.to_string())?;
        for line in exported.lines() {
            if !line.starts_with("import type ") {
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push('\n');
    }
    out.push_str(shared_abi_typescript_contracts());
    out.push('\n');
    out.push_str("export type RealtimeEnvelopeV1 = RealtimeEnvelope;\n");
    out.push_str("export type RealtimePayloadV1 = RealtimeDelta;\n");
    out.push_str("export type RealtimeVisibleEntity = VisibleEntity;\n");
    Ok(out)
}

fn shared_abi_typescript_contracts() -> &'static str {
    r#"export type AbiDirection = "North" | "South" | "East" | "West";
export type AbiResourceName = string;
export type AbiStructureType = string;
export type AbiActionPayload = { schema_hash: number[], payload: number[], };
export type PlayerMessage = { channel: "Player" | "Debug", text: string, };

export type CommandAction =
  | { type: "Move", object_id: number, direction: AbiDirection, }
  | { type: "Harvest", object_id: number, target_id: number, resource?: AbiResourceName, }
  | { type: "Transfer", object_id: number, target_id: number, resource: AbiResourceName, amount: number, }
  | { type: "Withdraw", object_id: number, target_id: number, resource: AbiResourceName, amount: number, }
  | { type: "Action", action_type: string, object_id: number, payload: AbiActionPayload, }
  | { type: "ClaimController", object_id: number, target_id: number, }
  | { type: "Spawn", object_id: number, spawn_id: number, body_parts: BodyPart[], }
  | { type: "Recycle", object_id: number, }
  | { type: "Build", object_id: number, structure: AbiStructureType, x: number, y: number, }
  | { type: "Repair", object_id: number, target_id: number, }
  | { type: "UpgradeController", object_id: number, target_id: number, }
  | { type: "TransferToGlobal", resource: AbiResourceName, amount: number, }
  | { type: "TransferFromGlobal", resource: AbiResourceName, amount: number, }
  | { type: "AlliedTransfer", target_player: number, resource: AbiResourceName, amount: number, };

export type CommandIntent = { sequence: number, idempotency_key: string, client_trace_id?: string, action: CommandAction, };
export type WorldConfigView = { config_hash: number[], payload: number[], };
export type FuelBudgetHints = { fuel_remaining: number, host_calls_remaining: number, output_bytes_remaining: number, };
export type MessageInboxCursor = { next_message_id: number, };
export type TickInput = { tick: number, player_id: number, world_id: number, visible_snapshot: number[], world_config_view: WorldConfigView, fuel_budget_hints: FuelBudgetHints, message_inbox_cursor: MessageInboxCursor, };
export type TickResult = { commands: CommandIntent[], messages: PlayerMessage[], };

"#
}

fn write_schema(path: std::path::PathBuf, schema: &schemars::Schema) -> Result<(), String> {
    let json = serde_json::to_string_pretty(schema).map_err(|error| error.to_string())?;
    write_if_changed(path, &(json + "\n"))
}

fn write_if_changed(path: std::path::PathBuf, contents: &str) -> Result<(), String> {
    if std::fs::read_to_string(&path).ok().as_deref() == Some(contents) {
        return Ok(());
    }
    std::fs::write(&path, contents).map_err(|error| format!("write {}: {error}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::components::TerrainType;
    use crate::mcp::{VisiblePosition, VisibleTile};
    use serde_json::json;
    use swarm_engine_api::{
        abi::{ActionPayload, CommandAction, Direction},
        ids::StructureTypeValue,
    };

    #[test]
    fn exports_runtime_contract_artifacts_without_wire_dtos_or_bigint() {
        let dir = tempfile::tempdir().unwrap();
        export_contract_artifacts(dir.path()).unwrap();

        let ts = std::fs::read_to_string(dir.path().join("swarm-contracts.ts")).unwrap();
        assert!(ts.contains("export type CommandIntent"));
        assert!(ts.contains("export type CommandAction"));
        assert!(ts.contains("export type RealtimeEnvelope"));
        assert!(ts.contains("export type VisibleWorldSnapshot"));
        assert!(!ts.contains("Wire"));
        assert!(!ts.contains("bigint"));
        assert!(ts.contains("type: \"Action\""));
        assert!(!dir.path().join("bindings").exists());

        let schema =
            std::fs::read_to_string(dir.path().join("command-intent.schema.json")).unwrap();
        assert!(schema.contains("CommandIntent"));
        assert!(schema.contains("Move"));
        assert!(schema.contains("AlliedTransfer"));
        assert!(!schema.contains("CommandIntentWire"));
        assert!(schema.contains("\"const\": \"Action\""));
        assert!(!schema.contains("bigint"));

        let schema_json: serde_json::Value = serde_json::from_str(&schema).unwrap();
        let action_branches = schema_json["$defs"]["CommandAction"]["oneOf"]
            .as_array()
            .unwrap();
        for branch in action_branches {
            let action_type = branch["properties"]["type"]["const"].as_str().unwrap();
            assert_eq!(
                branch["additionalProperties"],
                json!(false),
                "{action_type} schema branch must reject unknown fields"
            );
        }

        let realtime_schema =
            std::fs::read_to_string(dir.path().join("realtime.schema.json")).unwrap();
        let realtime_schema_json: serde_json::Value =
            serde_json::from_str(&realtime_schema).unwrap();
        assert_eq!(
            realtime_schema_json["properties"]["schema"],
            json!({"type": "string", "const": "swarm.realtime.v1"})
        );
        assert_eq!(realtime_schema_json["additionalProperties"], json!(false));
    }

    #[test]
    fn runtime_command_json_samples_match_exported_core_contract_shape() {
        let move_command = CommandIntent {
            sequence: 1,
            idempotency_key: "move-1".to_string(),
            client_trace_id: None,
            action: CommandAction::Move {
                object_id: 42,
                direction: Direction::North,
            },
        };
        assert_eq!(
            serde_json::to_value(move_command).unwrap(),
            json!({"sequence": 1, "idempotency_key": "move-1", "action": {"type": "Move", "object_id": 42, "direction": "North"}})
        );

        let build_command = CommandIntent {
            sequence: 2,
            idempotency_key: "build-2".to_string(),
            client_trace_id: Some("trace-2".to_string()),
            action: CommandAction::Build {
                object_id: 7,
                x: 3,
                y: 4,
                structure: StructureTypeValue::new("Extension"),
            },
        };
        assert_eq!(
            serde_json::to_value(build_command).unwrap(),
            json!({"sequence": 2, "idempotency_key": "build-2", "client_trace_id": "trace-2", "action": {"type": "Build", "object_id": 7, "structure": "Extension", "x": 3, "y": 4}})
        );

        let special = CommandIntent {
            sequence: 3,
            idempotency_key: "action-3".to_string(),
            client_trace_id: None,
            action: CommandAction::Action {
                action_type: "Attack".to_string(),
                object_id: 7,
                payload: ActionPayload::empty(),
            },
        };
        assert_eq!(
            serde_json::to_value(special).unwrap(),
            json!({"sequence": 3, "idempotency_key": "action-3", "action": {"type": "Action", "action_type": "Attack", "object_id": 7, "payload": {"schema_hash": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "payload": []}}})
        );
    }

    #[test]
    fn runtime_realtime_and_visible_json_samples_use_numeric_large_ints() {
        let delta = RealtimeDelta {
            tick: 9_007_199_254_740_991,
            last_tick: 9_007_199_254_740_990,
            player_id: 5,
            full_snapshot: true,
            changed_entities: Vec::new(),
            removed_entities: vec![123],
            state_checksum: 456,
        };
        assert_eq!(
            serde_json::to_value(RealtimeEnvelope {
                schema: "swarm.realtime.v1".to_string(),
                payload: delta,
            })
            .unwrap(),
            json!({
                "schema": "swarm.realtime.v1",
                "payload": {
                    "tick": 9007199254740991_u64,
                    "last_tick": 9007199254740990_u64,
                    "player_id": 5,
                    "full_snapshot": true,
                    "changed_entities": [],
                    "removed_entities": [123],
                    "state_checksum": 456
                }
            })
        );

        let tile = VisibleTile {
            x: 1,
            y: 2,
            room_id: 3,
            terrain: TerrainType::Plain,
        };
        assert_eq!(
            serde_json::to_value(tile).unwrap(),
            json!({"x": 1, "y": 2, "room_id": 3, "terrain": "Plain"})
        );

        let position = VisiblePosition {
            x: 1,
            y: 2,
            room_id: 3,
        };
        assert_eq!(
            serde_json::to_value(position).unwrap(),
            json!({"x": 1, "y": 2, "room_id": 3})
        );
    }
}
