//! SDK code generation from IDL.
//!
//! Generates TypeScript and Rust SDK code from an IdlDoc.
//! For TypeScript, custom actions are expanded as concrete action types
//! (方案β). For Rust, custom actions are generated as helper constructors
//! on CommandAction (the Rust equivalent of concrete types).

use crate::idl::{CommandDef, EnumDefs, IdlDoc, ModCustomAction};
use std::collections::BTreeMap;

// ── TypeScript generation ───────────────────────────────────────────

pub fn generate_typescript(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&ts_header(idl));
    out.push_str("\n");
    out.push_str(&ts_primitive_types());
    out.push_str("\n");
    out.push_str(&ts_enums(&idl.core.enums));
    out.push_str("\n");
    out.push_str(&ts_structure_types(idl));
    out.push_str("\n");
    out.push_str(&ts_core_actions(idl));
    out.push_str("\n");
    out.push_str(&ts_custom_actions(&idl.mods.custom_actions));
    out.push_str("\n");
    out.push_str(&ts_action_union(idl));
    out.push_str("\n");
    out.push_str(&ts_command_factories(idl));
    out.push_str("\n");
    out.push_str(&ts_constants(idl));
    out
}

fn ts_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn ts_primitive_types() -> String {
    r#"
export type UInt32 = number;
export type UInt64 = number | bigint;
export type PlayerId = UInt32;
export type RoomId = UInt32;
export type ObjectId = UInt64;
export type Tick = UInt64;
export type ResourceName = string;
export type ResourceAmount = UInt32;
export type ResourceCost = Record<ResourceName, ResourceAmount>;

export interface Position {
  x: number;
  y: number;
  room: RoomId;
}
"#
    .to_string()
}

fn ts_enums(enums: &EnumDefs) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("export type Direction = ");
    for (i, v) in enums.direction.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // BodyPart
    out.push_str("export type BodyPart = ");
    for (i, v) in enums.body_part.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // DamageType
    out.push_str("export type DamageType = ");
    for (i, v) in enums.damage_type.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // RejectionReason
    out.push_str("export type RejectionReasonCode = ");
    for (i, v) in enums.rejection_reason.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        if i % 8 == 0 && i > 0 {
            out.push_str("\n  | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n");

    out
}

fn ts_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::from("export type StructureType = ");
    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();
    for (i, s) in all.iter().enumerate() {
        if i > 0 {
            out.push_str("\n  | ");
        }
        out.push_str(&format!("\"{s}\""));
    }
    out.push_str(";\n");
    out
}

fn ts_core_actions(idl: &IdlDoc) -> String {
    let mut out = String::new();

    for cmd in &idl.core.commands {
        out.push_str(&format!(
            "export interface {name}Action {{\n",
            name = cmd.name
        ));
        out.push_str(&format!("  type: \"{name}\";\n", name = cmd.name));
        for (field, ftype) in &cmd.fields {
            let ts_type = idl_to_ts_type(ftype);
            out.push_str(&format!("  {field}: {ts_type};\n"));
        }
        out.push_str("}\n\n");
    }

    out
}

fn idl_to_ts_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "ObjectId".into(),
        "Direction" => "Direction".into(),
        "ResourceName" | "ResourceName?" => "ResourceName".into(),
        "ResourceAmount" => "ResourceAmount".into(),
        "u32" => "number".into(),
        "u64" => "number".into(),
        "i32" => "number".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "BodyPart[]".into(),
        other => {
            if let Some(base) = other.strip_suffix('?') {
                format!("{}", idl_to_ts_type(base)) // optional fields just omit the ?
            } else {
                format!("unknown /* {other} */")
            }
        }
    }
}

fn ts_custom_actions(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom actions (from world.toml mods) ──\n\n");

    for action in actions {
        out.push_str(&format!(
            "export interface {name}Action {{\n  type: \"{name}\";\n  object_id: ObjectId;\n  target_id: ObjectId;\n",
            name = action.name,
        ));
        // Optional fields based on action config
        if action.damage_type.is_some() {
            out.push_str("  damage_type?: DamageType;\n");
        }
        if action.cooldown.is_some() {
            out.push_str("  cooldown?: number;\n");
        }
        out.push_str("}\n\n");
    }

    out
}

fn ts_action_union(idl: &IdlDoc) -> String {
    let mut out = String::from("export type Action = ");

    let mut first = true;
    for cmd in &idl.core.commands {
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = cmd.name));
    }
    for action in &idl.mods.custom_actions {
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = action.name));
    }
    out.push_str(";\n\n");

    out
}

fn ts_command_factories(idl: &IdlDoc) -> String {
    let mut out = String::from(
        "export interface CommandIntent<A extends Action = Action> {\n  sequence: UInt32;\n  action: A;\n}\n\n",
    );

    out.push_str("export function command<A extends Action>(sequence: number, action: A): CommandIntent<A> {\n");
    out.push_str("  return { sequence, action };\n");
    out.push_str("}\n\n");

    out.push_str("export const actions = Object.freeze({\n");

    // Core command factories
    for cmd in &idl.core.commands {
        let fn_name = to_camel_case(&cmd.name);
        let args: Vec<String> = cmd
            .fields
            .iter()
            .map(|(f, t)| {
                let ts_type = idl_to_ts_type(t);
                let optional = t.ends_with('?');
                if optional {
                    format!("{f}?: {ts_type}")
                } else {
                    format!("{f}: {ts_type}")
                }
            })
            .collect();

        // SpawnDrone uses rename="Spawn" on wire
        let wire_type = if cmd.name == "SpawnDrone" {
            "Spawn"
        } else {
            &cmd.name
        };

        out.push_str(&format!(
            "  {fn_name}: ({args}) => ({{ type: \"{wire_type}\"",
            args = args.join(", ")
        ));
        for (field, _) in &cmd.fields {
            out.push_str(&format!(", {field}"));
        }
        out.push_str(" }) as const,\n");
    }

    // Custom action factories (方案β: concrete typed factories)
    for action in &idl.mods.custom_actions {
        let fn_name = to_camel_case(&action.name);
        out.push_str(&format!(
            "  {fn_name}: (object_id: ObjectId, target_id: ObjectId) =>\n    ({{ type: \"{name}\", object_id, target_id }}) as const,\n",
            fn_name = fn_name,
            name = action.name,
        ));
    }

    out.push_str("});\n\n");

    // body_energy_cost helper
    out.push_str(&format!(
        "export const BODY_PART_COST = Object.freeze({{\n{}}}\n) as const;\n\n",
        idl.core
            .body_part_costs
            .iter()
            .map(|(k, v)| format!("  {k}: {{ Energy: {v} }}"))
            .collect::<Vec<_>>()
            .join(",\n")
    ));

    out.push_str(
        r#"export function bodyCost(body: BodyPart[]): ResourceCost {
  const total: ResourceCost = {};
  for (const part of body) {
    const cost = BODY_PART_COST[part] ?? {};
    for (const [res, amt] of Object.entries(cost)) {
      total[res] = (total[res] ?? 0) + amt;
    }
  }
  return total;
}
"#,
    );

    out
}

fn ts_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("\n// ── Constants ──\n\n");
    out.push_str(&format!(
        "export const SDK_VERSION = \"{}\";\n",
        idl.engine_version
    ));
    out.push_str(&format!(
        "export const IDL_VERSION = \"{}\";\n",
        idl.idl_version
    ));
    out.push_str("export const ABI_VERSION = 1;\n\n");

    for (name, value) in &idl.core.constants {
        let js_val = match value {
            serde_json::Value::Number(n) => n.to_string(),
            serde_json::Value::Bool(b) => b.to_string(),
            _ => format!("{value}"),
        };
        out.push_str(&format!("export const {name} = {js_val};\n"));
    }

    out
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if i == 0 {
            result.push(c.to_lowercase().next().unwrap_or(c));
        } else {
            result.push(c);
        }
    }
    result
}

// ── Rust generation ─────────────────────────────────────────────────

pub fn generate_rust(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&rust_header(idl));
    out.push_str("\n");
    out.push_str(&rust_types());
    out.push_str("\n");
    out.push_str(&rust_enums(idl));
    out.push_str("\n");
    out.push_str(&rust_structure_types(idl));
    out.push_str("\n");
    out.push_str(&rust_command_action(idl));
    out.push_str("\n");
    out.push_str(&rust_command_struct());
    out.push_str("\n");
    out.push_str(&rust_custom_constructors(&idl.mods.custom_actions));
    out.push_str("\n");
    out.push_str(&rust_constants(idl));
    out
}

fn rust_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n\n\
         use serde::{{Deserialize, Serialize}};\n\
         use crate::types::{{BodyPart, ObjectId, ResourceAmount, ResourceName, StructureType}};\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn rust_types() -> String {
    "pub type PlayerId = u32;\npub type RoomId = u32;\npub type ObjectId = u64;\npub type Tick = u64;\npub type ResourceName = String;\npub type ResourceAmount = u32;\n".into()
}

fn rust_enums(idl: &IdlDoc) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum Direction {\n");
    for v in &idl.core.enums.direction {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");
    out.push_str(
        "impl Direction {\n    pub const fn offset(self) -> (i32, i32) {\n        match self {\n",
    );
    for v in &idl.core.enums.direction {
        let (dx, dy) = direction_offset(v);
        out.push_str(&format!("            Direction::{v} => ({dx}, {dy}),\n"));
    }
    out.push_str("        }\n    }\n}\n\n");

    // BodyPart
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum BodyPart {\n");
    for v in &idl.core.enums.body_part {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");

    // DamageType
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum DamageType {\n");
    for v in &idl.core.enums.damage_type {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n");

    out
}

fn direction_offset(v: &str) -> (i32, i32) {
    match v {
        "Top" => (0, -1),
        "TopRight" => (1, -1),
        "BottomRight" => (1, 0),
        "Bottom" => (0, 1),
        "BottomLeft" => (-1, 1),
        "TopLeft" => (-1, 0),
        _ => (0, 0),
    }
}

fn rust_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    out.push_str("pub struct StructureType(pub &'static str);\n\n");
    out.push_str("impl StructureType {\n");

    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();

    for s in &all {
        let const_name = s.to_uppercase().replace('-', "_");
        out.push_str(&format!(
            "    pub const {const_name}: Self = Self(\"{s}\");\n"
        ));
    }

    out.push_str("\n    pub fn new(name: impl Into<String>) -> Self {\n");
    out.push_str("        Self(Box::leak(name.into().into_boxed_str()))\n");
    out.push_str("    }\n\n");
    out.push_str("    pub fn as_str(self) -> &'static str { self.0 }\n");
    out.push_str("}\n");

    out
}

fn rust_command_action(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    out.push_str("#[serde(tag = \"type\")]\n");
    out.push_str("pub enum CommandAction {\n");

    for cmd in &idl.core.commands {
        let variant_name = &cmd.name;
        if cmd.fields.is_empty() {
            out.push_str(&format!("    {variant_name},\n"));
        } else {
            out.push_str(&format!("    {variant_name} {{\n"));
            for (field, ftype) in &cmd.fields {
                let rust_type = idl_to_rust_type(ftype);
                out.push_str(&format!("        {field}: {rust_type},\n"));
            }
            out.push_str("    },\n");
        }
    }

    // Custom variant (generic — mod actions go through here)
    out.push_str("    Custom {\n        action_type: String,\n        object_id: ObjectId,\n        target_id: Option<ObjectId>,\n        resource: Option<ResourceName>,\n        amount: Option<ResourceAmount>,\n        structure: Option<StructureType>,\n    },\n");

    out.push_str("}\n");
    out
}

fn idl_to_rust_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "ObjectId".into(),
        "Direction" => "Direction".into(),
        "ResourceName" => "ResourceName".into(),
        "ResourceName?" => "Option<ResourceName>".into(),
        "ResourceAmount" => "ResourceAmount".into(),
        "u32" => "u32".into(),
        "u64" => "u64".into(),
        "i32" => "i32".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "Vec<BodyPart>".into(),
        other => format!("String /* {other} */"),
    }
}

fn rust_command_struct() -> String {
    r#"
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Command {
    pub sequence: u32,
    pub action: CommandAction,
}
"#
    .to_string()
}

fn rust_custom_constructors(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom action constructors (方案β: typed helpers) ──\n\n");
    out.push_str("impl CommandAction {\n");

    for action in actions {
        let fn_name = action.name.to_lowercase();
        out.push_str(&format!(
            "    /// {description}\n    pub fn {fn_name}(object_id: ObjectId, target_id: ObjectId) -> Self {{\n        CommandAction::Custom {{\n            action_type: \"{name}\".into(),\n            object_id,\n            target_id: Some(target_id),\n            resource: None,\n            amount: None,\n            structure: None,\n        }}\n    }}\n\n",
            description = action.description,
            name = action.name,
            fn_name = fn_name,
        ));
    }

    out.push_str("}\n");
    out
}

fn rust_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("// ── Constants ──\n\n");

    for (name, value) in &idl.core.constants {
        match value {
            serde_json::Value::Number(n) => {
                if let Some(i) = n.as_u64() {
                    out.push_str(&format!("pub const {name}: u64 = {i};\n"));
                } else if let Some(f) = n.as_f64() {
                    out.push_str(&format!("pub const {name}: f64 = {f};\n"));
                }
            }
            _ => {}
        }
    }

    // Body part energy costs
    out.push_str("\npub const BODY_PART_COST: &[(BodyPart, u32)] = &[\n");
    for (name, cost) in &idl.core.body_part_costs {
        out.push_str(&format!("    (BodyPart::{name}, {cost}),\n"));
    }
    out.push_str("];\n\n");

    out.push_str(
        r#"pub fn body_energy_cost(body: &[BodyPart]) -> u32 {
    body.iter()
        .filter_map(|part| {
            BODY_PART_COST
                .iter()
                .find(|(p, _)| p == part)
                .map(|(_, cost)| *cost)
        })
        .sum()
}
"#,
    );

    out
}

// ── SDK cache path helpers ──────────────────────────────────────────

/// Compute the cache directory for a given world hash.
pub fn sdk_cache_dir(world_hash: &str) -> std::path::PathBuf {
    std::path::PathBuf::from("/data/swarm/sdk-cache").join(world_hash)
}

pub fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(data);
    format!("{:x}", hasher.finalize())
}

// ── CLI entry points ────────────────────────────────────────────────

use crate::world::WorldConfig;

/// CLI: dump IDL to stdout as JSON.
pub fn cli_dump_idl(world_toml_path: &str) -> Result<String, String> {
    let config = WorldConfig::from_world_toml(world_toml_path)
        .map_err(|e| format!("load world.toml: {e}"))?;
    let toml_bytes =
        std::fs::read(world_toml_path).map_err(|e| format!("read {world_toml_path}: {e}"))?;
    let world_hash = sha256_hex(&toml_bytes);

    let body_parts = crate::components::BodyPartRegistry::from_defs(config.body_part_types);
    let structures = crate::components::StructureTypeRegistry::default();
    let special_effects =
        crate::components::SpecialEffectRegistry::from_defs(config.special_effects);
    let custom_actions = crate::components::CustomActionRegistry::from_defs(config.custom_actions);

    let idl = crate::idl::extract_idl(
        &world_hash,
        &body_parts,
        &structures,
        &special_effects,
        &custom_actions,
    );

    serde_json::to_string_pretty(&idl).map_err(|e| format!("serialize IDL: {e}"))
}

/// CLI: generate SDK files to output directory.
pub fn cli_generate_sdk(world_toml_path: &str, out_base: &str) -> Result<(), String> {
    let idl_json = cli_dump_idl(world_toml_path)?;
    let idl: crate::idl::IdlDoc =
        serde_json::from_str(&idl_json).map_err(|e| format!("parse IDL: {e}"))?;

    let out_dir = std::path::PathBuf::from(out_base).join(&idl.world_hash);
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("create {}: {e}", out_dir.display()))?;

    // Generate TypeScript SDK
    let ts_code = generate_typescript(&idl);
    let ts_dir = out_dir.join("sdk-ts").join("src");
    std::fs::create_dir_all(&ts_dir).map_err(|e| format!("create {}: {e}", ts_dir.display()))?;
    std::fs::write(ts_dir.join("index.ts"), ts_code).map_err(|e| format!("write sdk-ts: {e}"))?;

    // Generate Rust SDK
    let rust_code = generate_rust(&idl);
    let rust_dir = out_dir.join("sdk-rust").join("src");
    std::fs::create_dir_all(&rust_dir)
        .map_err(|e| format!("create {}: {e}", rust_dir.display()))?;
    std::fs::write(rust_dir.join("commands.rs"), rust_code)
        .map_err(|e| format!("write sdk-rust: {e}"))?;

    // Write IDL itself
    std::fs::write(out_dir.join("idl.json"), idl_json)
        .map_err(|e| format!("write idl.json: {e}"))?;

    // Write metadata
    let meta = serde_json::json!({
        "world_hash": idl.world_hash,
        "engine_version": idl.engine_version,
        "idl_version": idl.idl_version,
        "generated_at": chrono_now(),
    });
    std::fs::write(
        out_dir.join("meta.json"),
        serde_json::to_string_pretty(&meta).unwrap(),
    )
    .map_err(|e| format!("write meta.json: {e}"))?;

    Ok(())
}

fn chrono_now() -> String {
    // Simple UTC timestamp without chrono dependency
    use std::time::SystemTime;
    match SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
        Ok(d) => format!("{}", d.as_secs()),
        Err(_) => "unknown".into(),
    }
}
