//! SDK code generation from IDL.
//!
//! Generates TypeScript and Rust SDK code from an IdlDoc.
//! For TypeScript, custom actions are expanded as concrete action types
//! (方案β). For Rust, custom actions are generated as helper constructors
//! on CommandAction (the Rust equivalent of concrete types).

use crate::{
    command::{
        CommandSchemaBranch, CommandSchemaField, SPECIAL_COMMAND_ACTIONS, command_schema_branches,
    },
    idl::{EnumDefs, IdlDoc, ModCustomAction},
};
use swarm_engine_api::abi::ABI_VERSION;
use swarm_engine_plugin_sdk::components::BodyPartRegistry;

// ── TypeScript generation ───────────────────────────────────────────

pub fn generate_typescript(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&ts_header(idl));
    out.push('\n');
    out.push_str(&ts_primitive_types());
    out.push('\n');
    out.push_str(&ts_enums(&idl.core.enums));
    out.push('\n');
    out.push_str(&ts_structure_types(idl));
    out.push('\n');
    out.push_str(&ts_core_actions(idl));
    out.push('\n');
    out.push_str(&ts_builtin_dispatch_actions());
    out.push('\n');
    out.push_str(&ts_custom_actions(&idl.mods.custom_actions));
    out.push('\n');
    out.push_str(&ts_action_union(idl));
    out.push('\n');
    out.push_str(&ts_command_factories(idl));
    out.push('\n');
    out.push_str(&ts_realtime_types());
    out.push('\n');
    out.push_str(&ts_constants(idl));
    out
}

fn ts_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn ts_primitive_types() -> String {
    r#"
export type UInt32 = number;
export type UInt64 = number | bigint;
export type PlayerId = UInt32;
export type RoomId = UInt32;
export type ObjectId = UInt64;
export type Tick = UInt64;
export type ResourceName = string;
export type ResourceAmount = UInt32;
export type ResourceCost = Record<ResourceName, ResourceAmount>;

export interface Position {
  x: number;
  y: number;
  room: RoomId;
}
"#
    .to_string()
}

fn ts_enums(enums: &EnumDefs) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("export type Direction = \"North\" | \"South\" | \"East\" | \"West\";\n\n");

    // BodyPart
    out.push_str("export type BodyPart = ");
    for (i, v) in enums.body_part.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // DamageType
    out.push_str("export type DamageType = ");
    for (i, v) in enums.damage_type.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // RejectionReason
    out.push_str("export type RejectionReasonCode = ");
    for (i, v) in enums.rejection_reason.iter().enumerate() {
        if i % 8 == 0 && i > 0 {
            out.push_str("\n  | ");
        } else if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n");

    out
}

fn ts_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::from("export type StructureType = ");
    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();
    for (i, s) in all.iter().enumerate() {
        if i > 0 {
            out.push_str("\n  | ");
        }
        out.push_str(&format!("\"{s}\""));
    }
    out.push_str(";\n");
    out
}

fn ts_core_actions(idl: &IdlDoc) -> String {
    let mut out = String::new();

    for cmd in &idl.core.commands {
        if cmd.name == "Action" || SPECIAL_COMMAND_ACTIONS.contains(&cmd.name.as_str()) {
            continue;
        }
        out.push_str(&format!(
            "export interface {name}Action {{\n",
            name = cmd.name
        ));
        out.push_str(&format!("  type: \"{name}\";\n", name = cmd.name));
        for (field, ftype) in &cmd.fields {
            let ts_type = idl_to_ts_type(ftype);
            let optional = if ftype.ends_with('?') { "?" } else { "" };
            out.push_str(&format!("  {field}{optional}: {ts_type};\n"));
        }
        out.push_str("}\n\n");
    }

    out
}

fn ts_builtin_dispatch_actions() -> String {
    let mut out = String::from("// ── Built-in ActionRegistry wire actions ──\n\n");
    for name in SPECIAL_COMMAND_ACTIONS {
        out.push_str(&format!(
            "export interface {name}Action {{\n  type: \"{name}\";\n{fields}}}\n\n",
            fields = ts_special_action_fields(),
        ));
    }
    out
}

fn ts_special_action_fields() -> &'static str {
    "  object_id: ObjectId;\n  target_id: ObjectId;\n  resource?: ResourceName;\n  amount?: ResourceAmount;\n  range?: number;\n  structure?: StructureType;\n  damage_type?: DamageType;\n  cooldown?: number;\n"
}

fn idl_to_ts_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "ObjectId".into(),
        "PlayerId" => "PlayerId".into(),
        "Direction" => "Direction".into(),
        "ResourceName" | "ResourceName?" => "ResourceName".into(),
        "ResourceAmount" => "ResourceAmount".into(),
        "u32" => "number".into(),
        "u64" => "UInt64".into(),
        "i32" => "number".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "BodyPart[]".into(),
        "String" => "string".into(),
        "JsonValue" => "unknown".into(),
        other => {
            if let Some(base) = other.strip_suffix('?') {
                idl_to_ts_type(base).to_string() // optional fields just omit the ?
            } else {
                format!("unknown /* {other} */")
            }
        }
    }
}

fn ts_custom_actions(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom actions (from world.toml mods) ──\n\n");

    for action in actions {
        if SPECIAL_COMMAND_ACTIONS.contains(&action.name.as_str()) {
            continue;
        }
        out.push_str(&format!(
            "export interface {name}Action {{\n  type: \"{name}\";\n  object_id: ObjectId;\n  target_id: ObjectId;\n",
            name = action.name,
        ));
        // Optional fields based on action config
        if action.damage_type.is_some() {
            out.push_str("  damage_type?: DamageType;\n");
        }
        if action.cooldown.is_some() {
            out.push_str("  cooldown?: number;\n");
        }
        out.push_str("}\n\n");
    }

    out
}

fn ts_action_union(idl: &IdlDoc) -> String {
    let mut out = String::from("export type Action = ");

    let mut first = true;
    for cmd in &idl.core.commands {
        if cmd.name == "Action" || SPECIAL_COMMAND_ACTIONS.contains(&cmd.name.as_str()) {
            continue;
        }
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = cmd.name));
    }
    for name in SPECIAL_COMMAND_ACTIONS {
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action"));
    }
    for action in &idl.mods.custom_actions {
        if SPECIAL_COMMAND_ACTIONS.contains(&action.name.as_str()) {
            continue;
        }
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = action.name));
    }
    out.push_str(";\n\n");

    out
}

fn ts_special_action_payload_type() -> &'static str {
    "export interface SpecialActionPayload {\n  resource?: ResourceName;\n  amount?: ResourceAmount;\n  range?: number;\n  structure?: StructureType;\n  damage_type?: DamageType;\n  cooldown?: number;\n}\n\n"
}

fn ts_command_factories(idl: &IdlDoc) -> String {
    let mut out = String::from(
        "export interface CommandIntent<A extends Action = Action> {\n  sequence: UInt32;\n  idempotency_key: string;\n  client_trace_id?: string;\n  action: A;\n}\n\nexport interface TickInput {\n  tick: UInt64;\n  player_id: PlayerId;\n  world_id: UInt64;\n  visible_snapshot: Uint8Array;\n  world_config_view: { config_hash: Uint8Array; payload: Uint8Array };\n  fuel_budget_hints: { fuel_remaining: UInt64; host_calls_remaining: UInt32; output_bytes_remaining: UInt32 };\n  message_inbox_cursor: { next_message_id: UInt64 };\n}\n\nexport interface TickResult<A extends Action = Action> {\n  commands: CommandIntent<A>[];\n  messages: PlayerMessage[];\n}\n\nexport interface PlayerMessage {\n  channel: \"Player\" | \"Debug\";\n  text: string;\n}\n\n",
    );
    out.push_str(ts_special_action_payload_type());
    // ---- addCost helper ----
    out.push_str(
        "export function addCost(target: ResourceCost, source: ResourceCost): ResourceCost {\n  for (const [res, amt] of Object.entries(source)) {\n    target[res] = (target[res] ?? 0) + amt;\n  }\n  return target;\n}\n\n",
    );
    // ---- command factory ----

    out.push_str("export function command<A extends Action>(sequence: number, idempotency_key: string, action: A, client_trace_id?: string): CommandIntent<A> {\n");
    out.push_str("  return client_trace_id === undefined ? { sequence, idempotency_key, action } : { sequence, idempotency_key, client_trace_id, action };\n");
    out.push_str("}\n\n");

    out.push_str("export const actions = Object.freeze({\n");

    // Core command factories
    for cmd in &idl.core.commands {
        if cmd.name == "Action" || SPECIAL_COMMAND_ACTIONS.contains(&cmd.name.as_str()) {
            continue;
        }
        let fn_name = to_camel_case(&cmd.name);
        let (required_fields, optional_fields): (Vec<_>, Vec<_>) =
            cmd.fields.iter().partition(|(_, t)| !t.ends_with('?'));
        let args: Vec<String> = required_fields
            .into_iter()
            .chain(optional_fields)
            .map(|(f, t)| {
                let ts_type = idl_to_ts_type(t);
                let optional = t.ends_with('?');
                if optional {
                    format!("{f}?: {ts_type}")
                } else {
                    format!("{f}: {ts_type}")
                }
            })
            .collect();

        // Spawn uses rename="Spawn" on wire
        let wire_type = if cmd.name == "Spawn" {
            "Spawn"
        } else {
            &cmd.name
        };

        out.push_str(&format!(
            "  {fn_name}: ({args}) => ({{ type: \"{wire_type}\"",
            args = args.join(", ")
        ));
        for (field, _) in &cmd.fields {
            out.push_str(&format!(", {field}"));
        }
        out.push_str(" }) as const,\n");
    }

    for name in SPECIAL_COMMAND_ACTIONS {
        let fn_name = to_camel_case(name);
        out.push_str(&format!(
            "  {fn_name}: (object_id: ObjectId, target_id: ObjectId, payload: SpecialActionPayload = {{}}) =>\n    ({{ type: \"{name}\", object_id, target_id, ...payload }}) as const,\n"
        ));
    }

    // Custom action factories (方案β: concrete typed factories)
    for action in &idl.mods.custom_actions {
        if SPECIAL_COMMAND_ACTIONS.contains(&action.name.as_str()) {
            continue;
        }
        let fn_name = to_camel_case(&action.name);
        let mut optional_args = Vec::new();
        let mut optional_fields = Vec::new();
        if action.damage_type.is_some() {
            optional_args.push("damage_type?: DamageType");
            optional_fields.push("damage_type");
        }
        if action.cooldown.is_some() {
            optional_args.push("cooldown?: number");
            optional_fields.push("cooldown");
        }
        let optional_args = if optional_args.is_empty() {
            String::new()
        } else {
            format!(", {}", optional_args.join(", "))
        };
        let optional_fields = if optional_fields.is_empty() {
            String::new()
        } else {
            format!(", {}", optional_fields.join(", "))
        };
        out.push_str(&format!(
            "  {fn_name}: (object_id: ObjectId, target_id: ObjectId{optional_args}) =>\n    ({{ type: \"{name}\", object_id, target_id{optional_fields} }}) as const,\n",
            fn_name = fn_name,
            name = action.name,
        ));
    }

    out.push_str("});\n\n");

    // body_energy_cost helper
    out.push_str(&format!(
        "export const BODY_PART_COST = {{\n{}\n}} as const;\n\n",
        idl.core
            .body_part_costs
            .iter()
            .map(|(k, v)| format!("  {k}: {{ Energy: {v} }}"))
            .collect::<Vec<_>>()
            .join(",\n")
    ));

    out.push_str(
        r#"export function bodyCost(body: BodyPart[]): ResourceCost {
  const total: ResourceCost = {};
  for (const part of body) {
    const cost = BODY_PART_COST[part] ?? {};
    for (const [res, amt] of Object.entries(cost)) {
      total[res] = (total[res] ?? 0) + amt;
    }
  }
  return total;
}
"#,
    );

    out
}

fn ts_realtime_types() -> String {
    r#"export interface RealtimePosition {
  x: number;
  y: number;
  room_id: RoomId;
}

export interface RealtimeVisibleEntity {
  type: "Drone" | "Structure" | "Source" | "Resource" | "Controller";
  id: ObjectId;
  position: RealtimePosition;
  owner?: PlayerId | null;
  structure_type?: string;
  body?: BodyPart[];
  carry?: ResourceCost;
  hits?: UInt32;
  energy?: UInt32 | null;
  produces?: ResourceCost;
  amounts?: ResourceCost;
  level?: UInt32;
}

export interface RealtimePayloadV1 {
  tick: Tick;
  last_tick: Tick;
  player_id: PlayerId;
  full_snapshot: boolean;
  changed_entities: RealtimeVisibleEntity[];
  removed_entities: ObjectId[];
  state_checksum: UInt64;
}

export interface RealtimeEnvelopeV1 {
  schema: "swarm.realtime.v1";
  payload: RealtimePayloadV1;
}
"#
    .to_string()
}

pub fn generate_command_intent_schema(_idl: &IdlDoc) -> serde_json::Value {
    serde_json::json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "Swarm tick() CommandIntent[]",
        "type": "array",
        "maxItems": 100,
        "items": { "$ref": "#/definitions/CommandIntent" },
        "definitions": {
            "CommandIntent": {
                "type": "object",
                "additionalProperties": false,
                "required": ["sequence", "idempotency_key", "action"],
                "properties": {
                    "sequence": { "type": "integer", "minimum": 0, "maximum": 4294967295_u64 },
                    "idempotency_key": { "type": "string", "minLength": 1 },
                    "client_trace_id": { "type": "string" },
                    "action": { "$ref": "#/definitions/Action" }
                }
            },
            "Action": {
                "oneOf": command_schema_branches()
                    .iter()
                    .map(command_schema_branch_schema)
                    .collect::<Vec<_>>()
            }
        }
    })
}

fn command_schema_branch_schema(branch: &CommandSchemaBranch) -> serde_json::Value {
    if branch.custom_wildcard {
        return serde_json::json!({
            "type": "object",
            "additionalProperties": true,
            "required": ["type", "object_id"],
            "propertyNames": {"not": {"enum": ["payload", "action_type", "action_name"]}},
            "properties": {
                "type": {"type": "string", "not": {"enum": reserved_command_action_names()}},
                "object_id": field_schema(&CommandSchemaField { name: "object_id", type_name: "ObjectId", required: true }),
                "target_id": field_schema(&CommandSchemaField { name: "target_id", type_name: "ObjectId", required: false }),
                "resource": field_schema(&CommandSchemaField { name: "resource", type_name: "ResourceName", required: false }),
                "amount": field_schema(&CommandSchemaField { name: "amount", type_name: "ResourceAmount", required: false }),
                "range": field_schema(&CommandSchemaField { name: "range", type_name: "u32", required: false }),
                "structure": field_schema(&CommandSchemaField { name: "structure", type_name: "StructureType", required: false }),
                "damage_type": field_schema(&CommandSchemaField { name: "damage_type", type_name: "DamageType", required: false }),
                "cooldown": field_schema(&CommandSchemaField { name: "cooldown", type_name: "u32", required: false })
            }
        });
    }
    let mut required = vec!["type".to_string()];
    required.extend(
        branch
            .fields
            .iter()
            .filter(|field| field.required)
            .map(|field| field.name.to_string()),
    );
    let mut properties = serde_json::Map::new();
    properties.insert(
        "type".to_string(),
        serde_json::json!({"const": branch.name}),
    );
    for field in &branch.fields {
        properties.insert(field.name.to_string(), field_schema(field));
    }
    serde_json::json!({
        "type": "object",
        "additionalProperties": false,
        "required": required,
        "properties": properties,
    })
}

fn reserved_command_action_names() -> Vec<&'static str> {
    command_schema_branches()
        .into_iter()
        .filter(|branch| !branch.custom_wildcard)
        .map(|branch| branch.name)
        .collect()
}

fn field_schema(field: &CommandSchemaField) -> serde_json::Value {
    match field.type_name {
        "ObjectId" => serde_json::json!({"type": "integer", "minimum": 0}),
        "PlayerId" | "ResourceAmount" | "u32" => {
            serde_json::json!({"type": "integer", "minimum": 0, "maximum": 4294967295_u64})
        }
        "Direction" => {
            serde_json::json!({"type": "string", "enum": ["North", "South", "East", "West"]})
        }
        "ResourceName" | "StructureType" | "DamageType" => serde_json::json!({"type": "string"}),
        "u64" => serde_json::json!({"type": "integer", "minimum": 0}),
        "i32" => serde_json::json!({"type": "integer"}),
        "BodyPart[]" => {
            serde_json::json!({"type": "array", "items": {"type": "string", "enum": ["Move", "Work", "Carry", "Attack", "RangedAttack", "Heal", "Claim", "Tough"]}, "minItems": 1, "maxItems": crate::command::MAX_BODY_PARTS})
        }
        "JsonValue" => serde_json::json!(true),
        _ => serde_json::json!({"type": "string"}),
    }
}

fn ts_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("\n// ── Constants ──\n\n");
    out.push_str(&format!(
        "export const SDK_VERSION = \"{}\";\n",
        idl.engine_version
    ));
    out.push_str(&format!(
        "export const IDL_VERSION = \"{}\";\n",
        idl.idl_version
    ));
    out.push_str(&format!("export const ABI_VERSION = {ABI_VERSION};\n\n"));
    // AI game data markers (used by tick protocol)
    out.push_str("export const AI_GAME_DATA_START = \"___AI_GAME_DATA_START___\";\n");
    out.push_str("export const AI_GAME_DATA_END = \"___AI_GAME_DATA_END___\";\n\n");

    for (name, value) in &idl.core.constants {
        let js_val = match value {
            serde_json::Value::Number(n) => integer_constant(name, n).literal(),
            serde_json::Value::Bool(b) => b.to_string(),
            _ => format!("{value}"),
        };
        out.push_str(&format!("export const {name} = {js_val};\n"));
    }

    out
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if i == 0 {
            result.push(c.to_lowercase().next().unwrap_or(c));
        } else {
            result.push(c);
        }
    }
    result
}

// ── Rust generation ─────────────────────────────────────────────────

pub fn generate_rust(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&rust_header(idl));
    out.push('\n');
    // Type aliases live in types_template.rs; only enums + commands generated here.
    out.push_str(&rust_enums(idl));
    out.push('\n');
    out.push_str(&rust_structure_types(idl));
    out.push('\n');
    out.push_str(&rust_command_action(idl));
    out.push('\n');
    out.push_str(&rust_command_struct());
    out.push('\n');
    out.push_str(&rust_custom_constructors(&idl.mods.custom_actions));
    out.push('\n');
    out.push_str(&rust_constants(idl));
    out
}

fn rust_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n\n\
         use serde::{{Deserialize, Serialize}};\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn rust_enums(idl: &IdlDoc) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum Direction {\n");
    for v in &idl.core.enums.direction {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");
    out.push_str(
        "impl Direction {\n    pub const fn offset(self) -> (i32, i32) {\n        match self {\n",
    );
    for v in &idl.core.enums.direction {
        let (dx, dy) = direction_offset(v);
        out.push_str(&format!("            Direction::{v} => ({dx}, {dy}),\n"));
    }
    out.push_str("        }\n    }\n}\n\n");

    // BodyPart
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum BodyPart {\n");
    for v in &idl.core.enums.body_part {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");

    // DamageType
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum DamageType {\n");
    for v in &idl.core.enums.damage_type {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n");

    out
}

fn direction_offset(v: &str) -> (i32, i32) {
    match v {
        "Top" => (0, -1),
        "TopRight" => (1, -1),
        "BottomRight" => (1, 0),
        "Bottom" => (0, 1),
        "BottomLeft" => (-1, 1),
        "TopLeft" => (-1, 0),
        _ => (0, 0),
    }
}

fn rust_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    out.push_str("pub struct StructureType(pub &'static str);\n\n");
    out.push_str("impl StructureType {\n");

    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();

    for s in &all {
        let const_name = s.to_uppercase().replace('-', "_");
        out.push_str(&format!(
            "    pub const {const_name}: Self = Self(\"{s}\");\n"
        ));
    }

    out.push_str("\n    pub fn new(name: impl Into<String>) -> Self {\n");
    out.push_str("        Self(Box::leak(name.into().into_boxed_str()))\n");
    out.push_str("    }\n\n");
    out.push_str("    pub fn as_str(self) -> &'static str {\n        self.0\n    }\n");

    // Add PascalCase aliases (backward compat)
    for s in &all {
        if s.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
            out.push_str(&format!(
                "    #[allow(non_upper_case_globals)]\n    pub const {s}: Self = Self::{};\n",
                s.to_uppercase().replace('-', "_")
            ));
        }
    }
    out.push_str("}\n\n");

    // Custom Serialize / Deserialize (same pattern as engine's StructureType)
    out.push_str("impl Serialize for StructureType {\n");
    out.push_str(
        "    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {\n",
    );
    out.push_str("        s.serialize_str(self.0)\n    }\n}\n\n");
    out.push_str("impl<'de> Deserialize<'de> for StructureType {\n");
    out.push_str(
        "    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {\n",
    );
    out.push_str("        String::deserialize(d).map(Self::new)\n    }\n}\n\n");
    out.push_str("impl std::fmt::Display for StructureType {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        f.write_str(self.0)\n    }\n}\n\n");
    out.push_str("impl Default for StructureType {\n");
    out.push_str("    fn default() -> Self {\n        Self::SPAWN\n    }\n}\n");

    out
}

fn rust_command_action(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    out.push_str("#[serde(tag = \"type\", deny_unknown_fields)]\n");
    out.push_str("pub enum CommandAction {\n");

    for cmd in &idl.core.commands {
        if cmd.name == "Action" || SPECIAL_COMMAND_ACTIONS.contains(&cmd.name.as_str()) {
            continue;
        }
        let variant_name = &cmd.name;
        if cmd.fields.is_empty() {
            out.push_str(&format!("    {variant_name},\n"));
        } else {
            out.push_str(&format!("    {variant_name} {{\n"));
            for (field, ftype) in &cmd.fields {
                let rust_type = idl_to_rust_type(ftype);
                out.push_str(&format!("        {field}: {rust_type},\n"));
            }
            out.push_str("    },\n");
        }
    }

    for name in SPECIAL_COMMAND_ACTIONS {
        out.push_str(&format!(
            "    {name} {{\n{fields}    }},\n",
            fields = rust_special_action_fields(),
        ));
    }

    for action in &idl.mods.custom_actions {
        if SPECIAL_COMMAND_ACTIONS.contains(&action.name.as_str()) {
            continue;
        }
        out.push_str(&format!(
            "    {name} {{\n        object_id: u64,\n        target_id: u64,\n",
            name = action.name
        ));
        if action.damage_type.is_some() {
            out.push_str("        damage_type: Option<DamageType>,\n");
        }
        if action.cooldown.is_some() {
            out.push_str("        cooldown: Option<u32>,\n");
        }
        out.push_str("    },\n");
    }

    out.push_str("}\n");
    out
}

fn rust_special_action_fields() -> &'static str {
    "        object_id: u64,\n        target_id: u64,\n        resource: Option<String>,\n        amount: Option<u32>,\n        range: Option<u32>,\n        structure: Option<StructureType>,\n        damage_type: Option<DamageType>,\n        cooldown: Option<u32>,\n"
}

fn idl_to_rust_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "u64".into(),
        "ObjectId?" => "Option<u64>".into(),
        "PlayerId" => "u32".into(),
        "PlayerId?" => "Option<u32>".into(),
        "Direction" => "Direction".into(),
        "ResourceName" => "String".into(),
        "ResourceName?" => "Option<String>".into(),
        "ResourceAmount" => "u32".into(),
        "u32" => "u32".into(),
        "u64" => "u64".into(),
        "u64?" => "Option<u64>".into(),
        "i32" => "i32".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "Vec<BodyPart>".into(),
        "String" => "String".into(),
        "JsonValue" => "serde_json::Value".into(),
        other => format!("String /* {other} */"),
    }
}

fn rust_command_struct() -> String {
    r#"#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommandIntent {
    pub sequence: u32,
    pub idempotency_key: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub client_trace_id: Option<String>,
    pub action: CommandAction,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TickInput {
    pub tick: u64,
    pub player_id: u32,
    pub world_id: u64,
    pub visible_snapshot: Vec<u8>,
    pub world_config_view: WorldConfigView,
    pub fuel_budget_hints: FuelBudgetHints,
    pub message_inbox_cursor: MessageInboxCursor,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct WorldConfigView {
    pub config_hash: [u8; 32],
    pub payload: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct FuelBudgetHints {
    pub fuel_remaining: u64,
    pub host_calls_remaining: u32,
    pub output_bytes_remaining: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct MessageInboxCursor {
    pub next_message_id: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct TickResult {
    pub commands: Vec<CommandIntent>,
    #[serde(default)]
    pub messages: Vec<PlayerMessage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PlayerMessage {
    pub topic: String,
    pub payload: Vec<u8>,
}
"#
    .to_string()
}

fn rust_custom_constructors(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom action constructors (方案β: typed helpers) ──\n\n");
    out.push_str("impl CommandAction {\n");

    for (index, action) in actions.iter().enumerate() {
        if SPECIAL_COMMAND_ACTIONS.contains(&action.name.as_str()) {
            continue;
        }
        let fn_name = action.name.to_lowercase();
        let mut optional_defaults = String::new();
        if action.damage_type.is_some() {
            optional_defaults.push_str("\n            damage_type: None,");
        }
        if action.cooldown.is_some() {
            optional_defaults.push_str("\n            cooldown: None,");
        }
        out.push_str(&format!(
            "    /// {description}\n    pub fn {fn_name}(object_id: u64, target_id: u64) -> Self {{\n        CommandAction::{name} {{\n            object_id,\n            target_id,{optional_defaults}\n        }}\n    }}\n",
            description = action.description,
            name = action.name,
            fn_name = fn_name,
            optional_defaults = optional_defaults,
        ));
        if index + 1 < actions.len() {
            out.push('\n');
        }
    }

    out.push_str("}\n");
    out
}

fn rust_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("// ── Constants ──\n\n");

    for (name, value) in &idl.core.constants {
        if let serde_json::Value::Number(n) = value {
            match integer_constant(name, n) {
                IntegerConstant::Unsigned(value) => {
                    out.push_str(&format!("pub const {name}: u64 = {value};\n"));
                }
                IntegerConstant::Signed(value) => {
                    out.push_str(&format!("pub const {name}: i64 = {value};\n"));
                }
            }
        }
    }

    // Body part energy costs
    out.push_str("\npub const BODY_PART_COST: &[(BodyPart, u32)] = &[\n");
    for (name, cost) in &idl.core.body_part_costs {
        out.push_str(&format!("    (BodyPart::{name}, {cost}),\n"));
    }
    out.push_str("];\n\n");

    out.push_str(
        r#"pub fn body_energy_cost(body: &[BodyPart]) -> u32 {
    body.iter()
        .filter_map(|part| {
            BODY_PART_COST
                .iter()
                .find(|(p, _)| p == part)
                .map(|(_, cost)| *cost)
        })
        .sum()
}
"#,
    );

    out
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum IntegerConstant {
    Unsigned(u64),
    Signed(i64),
}

impl IntegerConstant {
    fn literal(self) -> String {
        match self {
            Self::Unsigned(value) => value.to_string(),
            Self::Signed(value) => value.to_string(),
        }
    }
}

fn integer_constant(name: &str, number: &serde_json::Number) -> IntegerConstant {
    if let Some(value) = number.as_u64() {
        return IntegerConstant::Unsigned(value);
    }
    if let Some(value) = number.as_i64() {
        return IntegerConstant::Signed(value);
    }

    decimal_integer_constant(&number.to_string()).unwrap_or_else(|| {
        panic!("gameplay constant {name} must use a fixed-point integer, got {number}")
    })
}

fn decimal_integer_constant(value: &str) -> Option<IntegerConstant> {
    const MAX_EXACT_INTEGER: u64 = 9_007_199_254_740_991;

    let (negative, unsigned) = value
        .strip_prefix('-')
        .map_or((false, value), |value| (true, value));
    let (mantissa, exponent) = match unsigned.split_once(['e', 'E']) {
        Some((mantissa, exponent)) => (mantissa, exponent.parse::<i32>().ok()?),
        None => (unsigned, 0_i32),
    };
    let mut digits = String::with_capacity(mantissa.len());
    let mut fractional_digits = 0_i32;
    let mut decimal_seen = false;
    for character in mantissa.chars() {
        match character {
            '0'..='9' => {
                digits.push(character);
                if decimal_seen {
                    fractional_digits += 1;
                }
            }
            '.' if !decimal_seen => decimal_seen = true,
            _ => return None,
        }
    }
    if digits.is_empty() {
        return None;
    }

    let scale = exponent.checked_sub(fractional_digits)?;
    if scale >= 0 {
        if scale > 20 {
            return None;
        }
        digits.extend(std::iter::repeat_n('0', scale as usize));
    } else {
        let removed_digits = scale.unsigned_abs() as usize;
        if removed_digits > digits.len() {
            if digits.bytes().any(|digit| digit != b'0') {
                return None;
            }
            digits.clear();
            digits.push('0');
        } else {
            let split = digits.len() - removed_digits;
            if digits[split..].bytes().any(|digit| digit != b'0') {
                return None;
            }
            digits.truncate(split);
            if digits.is_empty() {
                digits.push('0');
            }
        }
    }

    let magnitude = digits.parse::<u64>().ok()?;
    if magnitude > MAX_EXACT_INTEGER {
        return None;
    }
    if negative && magnitude != 0 {
        Some(IntegerConstant::Signed(-(magnitude as i64)))
    } else {
        Some(IntegerConstant::Unsigned(magnitude))
    }
}

// ── SDK cache path helpers ──────────────────────────────────────────

/// Compute the cache directory for a given world hash.
pub fn sdk_cache_dir(world_hash: &str) -> std::path::PathBuf {
    std::path::PathBuf::from("/data/swarm/sdk-cache").join(world_hash)
}

/// Return the engine source dir path.
fn engine_dir() -> Result<std::path::PathBuf, String> {
    let exe = std::env::current_exe().map_err(|e| format!("current_exe: {e}"))?;
    // Walk up from the binary to find the engine src/ directory
    for ancestor in exe.ancestors().take(10) {
        let path = ancestor.join("sdk-templates");
        if path.is_dir() {
            return Ok(path.to_path_buf());
        }
    }
    // Fallback: check relative to CWD
    let cwd_templates = std::env::current_dir()
        .unwrap_or_default()
        .join("sdk-templates");
    if cwd_templates.is_dir() {
        return Ok(cwd_templates);
    }
    Err("Cannot locate engine sdk-templates directory".into())
}

/// Copy all template files from engine/sdk-templates/<lang>/ into the output SDK directory.
fn merge_sdk_templates(lang: &str, out_dir: &std::path::Path) -> Result<(), String> {
    let templates_dir = engine_dir()?.join(lang);
    if !templates_dir.is_dir() {
        return Err(format!(
            "sdk-templates/{lang} not found at {}",
            templates_dir.display()
        ));
    }
    copy_dir(&templates_dir, out_dir).map_err(|e| format!("copy sdk-templates/{lang}: {e}"))?;
    Ok(())
}

/// Recursive directory copy. Overwrites existing files.
fn copy_dir(src: &std::path::Path, dst: &std::path::Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| format!("mkdir {}: {e}", dst.display()))?;
    for entry in std::fs::read_dir(src).map_err(|e| format!("readdir {}: {e}", src.display()))? {
        let entry = entry.map_err(|e| format!("entry: {e}"))?;
        let file_name = entry.file_name();
        if matches!(
            file_name.to_str(),
            Some("node_modules" | "dist" | "target" | ".git" | "package-lock.json" | "Cargo.lock")
        ) {
            continue;
        }
        let src_path = entry.path();
        let dst_path = dst.join(file_name);
        if src_path.is_dir() {
            copy_dir(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path).map_err(|e| {
                format!("copy {} -> {}: {e}", src_path.display(), dst_path.display())
            })?;
        }
    }
    Ok(())
}

pub fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(data);
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

// ── CLI entry points ────────────────────────────────────────────────

use crate::world::WorldConfig;

/// CLI: dump IDL to stdout as JSON.
pub fn cli_dump_idl(world_toml_path: &str) -> Result<String, String> {
    let config = WorldConfig::from_world_toml(world_toml_path)
        .map_err(|e| format!("load world.toml: {e}"))?;
    let toml_bytes =
        std::fs::read(world_toml_path).map_err(|e| format!("read {world_toml_path}: {e}"))?;
    let world_hash = sha256_hex(&toml_bytes);

    let body_parts = BodyPartRegistry::from_defs(config.body_part_types);
    let structures = crate::components::StructureTypeRegistry::default();
    let special_effects =
        crate::components::SpecialEffectRegistry::from_defs(config.special_effects);
    let custom_actions = crate::components::CustomActionRegistry::from_defs(config.custom_actions);

    let idl = crate::idl::extract_idl(
        &world_hash,
        &body_parts,
        &structures,
        &special_effects,
        &custom_actions,
    );

    serde_json::to_string_pretty(&idl).map_err(|e| format!("serialize IDL: {e}"))
}

/// CLI: generate SDK files to output directory.
pub fn cli_generate_sdk(world_toml_path: &str, out_base: &str) -> Result<(), String> {
    let idl_json = cli_dump_idl(world_toml_path)?;
    let idl: crate::idl::IdlDoc =
        serde_json::from_str(&idl_json).map_err(|e| format!("parse IDL: {e}"))?;

    let out_dir = std::path::PathBuf::from(out_base).join(&idl.world_hash);
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("create {}: {e}", out_dir.display()))?;

    // Merge templates with generated code for TypeScript
    let ts_code = generate_typescript(&idl);
    let ts_sdk_dir = out_dir.join("sdk-ts");
    merge_sdk_templates("ts", &ts_sdk_dir)?;
    let ts_src = ts_sdk_dir.join("src");
    std::fs::create_dir_all(&ts_src).map_err(|e| format!("create {}: {e}", ts_src.display()))?;
    std::fs::write(ts_src.join("commands.ts"), ts_code)
        .map_err(|e| format!("write sdk-ts/commands.ts: {e}"))?;
    std::fs::write(
        ts_src.join("command-intent.schema.json"),
        serde_json::to_string_pretty(&generate_command_intent_schema(&idl)).unwrap(),
    )
    .map_err(|e| format!("write sdk-ts/command-intent.schema.json: {e}"))?;

    // Merge templates with generated code for Rust
    let rust_code = generate_rust(&idl);
    let rust_sdk_dir = out_dir.join("sdk-rust");
    merge_sdk_templates("rust", &rust_sdk_dir)?;
    let rust_src = rust_sdk_dir.join("src");
    std::fs::create_dir_all(&rust_src)
        .map_err(|e| format!("create {}: {e}", rust_src.display()))?;
    std::fs::write(rust_src.join("commands.rs"), rust_code)
        .map_err(|e| format!("write sdk-rust/commands.rs: {e}"))?;

    // Write IDL itself
    std::fs::write(out_dir.join("idl.json"), idl_json)
        .map_err(|e| format!("write idl.json: {e}"))?;

    // Write metadata
    let meta = serde_json::json!({
        "world_hash": idl.world_hash,
        "engine_version": idl.engine_version,
        "idl_version": idl.idl_version,
        "generated_at": chrono_now(),
    });
    std::fs::write(
        out_dir.join("meta.json"),
        serde_json::to_string_pretty(&meta).unwrap(),
    )
    .map_err(|e| format!("write meta.json: {e}"))?;

    Ok(())
}

fn chrono_now() -> String {
    // Simple UTC timestamp without chrono dependency
    use std::time::SystemTime;
    match SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
        Ok(d) => format!("{}", d.as_secs()),
        Err(_) => "unknown".into(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::idl::{CommandDef, CoreIdl, EnumDefs, ModIdl};
    use indexmap::IndexMap;
    use std::collections::BTreeMap;

    fn minimal_idl() -> IdlDoc {
        IdlDoc {
            idl_version: "1".to_string(),
            world_hash: "hash".to_string(),
            engine_version: "0.1.0".to_string(),
            core: CoreIdl {
                commands: vec![CommandDef {
                    name: "Wait".to_string(),
                    fields: IndexMap::from([("until".to_string(), "u64".to_string())]),
                    metadata: BTreeMap::new(),
                }],
                enums: EnumDefs {
                    direction: vec!["North".to_string()],
                    body_part: vec!["Move".to_string()],
                    damage_type: vec!["Kinetic".to_string()],
                    rejection_reason: vec![],
                },
                structure_types: vec!["Spawn".to_string()],
                constants: BTreeMap::new(),
                body_part_costs: BTreeMap::new(),
            },
            mods: ModIdl {
                custom_actions: vec![
                    ModCustomAction {
                        name: "Debilitate".to_string(),
                        description: "reserved special shadow".to_string(),
                        damage_type: Some("EMP".to_string()),
                        base_damage: Some(10),
                        range: 3,
                        special_effect: None,
                        special_param_micro: None,
                        cooldown: Some(5),
                        cost: BTreeMap::new(),
                    },
                    ModCustomAction {
                        name: "Blink".to_string(),
                        description: "blink target".to_string(),
                        damage_type: Some("EMP".to_string()),
                        base_damage: None,
                        range: 3,
                        special_effect: None,
                        special_param_micro: None,
                        cooldown: Some(5),
                        cost: BTreeMap::new(),
                    },
                ],
                special_effects: vec![],
                body_parts: vec![],
                structure_types: vec![],
            },
        }
    }

    #[test]
    fn generated_constants_convert_exact_legacy_float_integers() {
        let mut idl = minimal_idl();
        idl.core
            .constants
            .insert("LEGACY_LIMIT".to_string(), serde_json::json!(12.0));
        idl.core
            .constants
            .insert("SIGNED_OFFSET".to_string(), serde_json::json!(-3));

        let typescript = generate_typescript(&idl);
        let rust = generate_rust(&idl);

        assert!(typescript.contains("export const LEGACY_LIMIT = 12;"));
        assert!(typescript.contains("export const SIGNED_OFFSET = -3;"));
        assert!(rust.contains("pub const LEGACY_LIMIT: u64 = 12;"));
        assert!(rust.contains("pub const SIGNED_OFFSET: i64 = -3;"));
    }

    #[test]
    #[should_panic(expected = "gameplay constant DAMAGE_MULTIPLIER must use a fixed-point integer")]
    fn generated_constants_reject_fractional_gameplay_values() {
        let mut idl = minimal_idl();
        idl.core
            .constants
            .insert("DAMAGE_MULTIPLIER".to_string(), serde_json::json!(1.25));

        let _ = generate_typescript(&idl);
    }

    #[test]
    fn generated_sdks_use_canonical_u64_and_custom_action_shapes() {
        let mut idl = minimal_idl();
        idl.core.commands.push(CommandDef {
            name: "Harvest".to_string(),
            fields: IndexMap::from([
                ("object_id".to_string(), "ObjectId".to_string()),
                ("resource".to_string(), "ResourceName?".to_string()),
            ]),
            metadata: BTreeMap::new(),
        });
        idl.core.commands.push(CommandDef {
            name: "AlliedTransfer".to_string(),
            fields: IndexMap::from([
                ("target_player".to_string(), "PlayerId".to_string()),
                ("resource".to_string(), "ResourceName".to_string()),
                ("amount".to_string(), "ResourceAmount".to_string()),
            ]),
            metadata: BTreeMap::new(),
        });
        let ts = generate_typescript(&idl);
        assert!(ts.contains("until: UInt64"));
        assert!(ts.contains("resource?: ResourceName"));
        assert!(ts.contains("target_player: PlayerId"));
        assert!(ts.contains("export interface AttackAction"));
        assert!(ts.contains("resource?: ResourceName"));
        assert!(ts.contains("structure?: StructureType"));
        assert!(ts.contains("export interface RangedAttackAction"));
        assert!(ts.contains("export interface HealAction"));
        assert!(ts.contains("export interface DebilitateAction"));
        assert!(ts.contains("export interface BlinkAction"));
        assert!(ts.contains("payload: SpecialActionPayload = {}"));
        assert!(ts.contains("export interface RealtimeEnvelopeV1"));
        assert!(ts.contains("schema: \"swarm.realtime.v1\""));
        assert!(!ts.contains("export interface ActionAction"));
        assert!(!ts.contains("type: \"Action\""));

        let rust = generate_rust(&idl);
        assert!(rust.contains(
            "Debilitate {\n        object_id: u64,\n        target_id: u64,\n        resource: Option<String>,"
        ));
        assert!(rust.contains("#[serde(tag = \"type\", deny_unknown_fields)]"));
        assert!(rust.contains("target_player: u32"));
        assert!(rust.contains("Attack {\n        object_id: u64,\n        target_id: u64,"));
        assert!(rust.contains("structure: Option<StructureType>"));
        assert!(rust.contains("Blink {\n        object_id: u64,\n        target_id: u64,"));
        assert!(rust.contains("damage_type: Option<DamageType>"));
        assert!(rust.contains("cooldown: Option<u32>"));
        assert!(rust.contains("CommandAction::Blink"));
        assert!(rust.contains("pub struct CommandIntent"));
        assert!(rust.contains("pub idempotency_key: String"));
        assert!(rust.contains("pub struct TickInput"));
        assert!(rust.contains("pub struct TickResult"));
        assert!(!rust.contains("pub type Command = CommandIntent"));
        assert!(!rust.contains("    Action {"));

        let schema = generate_command_intent_schema(&idl);
        assert_eq!(
            schema["definitions"]["CommandIntent"]["required"],
            serde_json::json!(["sequence", "idempotency_key", "action"])
        );
        assert_eq!(schema["items"]["$ref"], "#/definitions/CommandIntent");
        let branches = schema["definitions"]["Action"]["oneOf"]
            .as_array()
            .expect("schema should expose action oneOf branches");
        assert_eq!(branches.len(), command_schema_branches().len());
        assert_eq!(branches.len(), 25);
        let concrete_names = branches
            .iter()
            .filter_map(|branch| branch["properties"]["type"]["const"].as_str())
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(concrete_names.len(), 24);
        assert!(concrete_names.contains("TransferToGlobal"));
        assert!(!concrete_names.contains("DefaultLoan"));
        assert!(concrete_names.contains("Hack"));
        let wildcard = branches
            .iter()
            .find(|branch| branch["properties"]["type"]["not"]["enum"].is_array())
            .expect("schema should expose one custom wildcard branch");
        let reserved = wildcard["properties"]["type"]["not"]["enum"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(serde_json::Value::as_str)
            .collect::<std::collections::BTreeSet<_>>();
        assert_eq!(reserved.len(), concrete_names.len());
        assert!(reserved.contains("Move"));
        assert!(reserved.contains("Hack"));
        assert!(!reserved.contains("DefaultLoan"));
    }

    #[test]
    fn template_copy_excludes_build_and_dependency_artifacts() {
        let source = tempfile::tempdir().unwrap();
        let output = tempfile::tempdir().unwrap();
        std::fs::create_dir(source.path().join("src")).unwrap();
        std::fs::create_dir(source.path().join("node_modules")).unwrap();
        std::fs::create_dir(source.path().join("dist")).unwrap();
        std::fs::create_dir(source.path().join("target")).unwrap();
        std::fs::write(source.path().join("src/index.ts"), "export {};\n").unwrap();
        std::fs::write(source.path().join("node_modules/stale.js"), "stale").unwrap();
        std::fs::write(source.path().join("package-lock.json"), "{}").unwrap();

        copy_dir(source.path(), output.path()).unwrap();

        assert!(output.path().join("src/index.ts").is_file());
        assert!(!output.path().join("node_modules").exists());
        assert!(!output.path().join("dist").exists());
        assert!(!output.path().join("target").exists());
        assert!(!output.path().join("package-lock.json").exists());
    }

    #[test]
    fn freshly_generated_typescript_and_rust_sdks_compile() {
        let output = tempfile::tempdir().unwrap();
        cli_generate_sdk("world.toml", output.path().to_str().unwrap()).unwrap();
        let world_dir = std::fs::read_dir(output.path())
            .unwrap()
            .next()
            .expect("generator should create a world hash directory")
            .unwrap()
            .path();
        let generated_ts =
            std::fs::read_to_string(world_dir.join("sdk-ts/src/commands.ts")).unwrap();
        assert!(generated_ts.contains("idempotency_key: string"));
        assert!(generated_ts.contains("\"CapacityExceeded\""));
        assert!(
            generated_ts
                .contains("export type Direction = \"North\" | \"South\" | \"East\" | \"West\"")
        );
        assert!(!generated_ts.contains("TopRight"));

        let templates = engine_dir().unwrap();
        let tsc = templates.join("ts/node_modules/.bin/tsc");
        assert!(tsc.is_file(), "TypeScript dependencies must be installed");
        let ts_output = std::process::Command::new(tsc)
            .args([
                "-p",
                world_dir.join("sdk-ts/tsconfig.json").to_str().unwrap(),
            ])
            .output()
            .unwrap();
        assert!(
            ts_output.status.success(),
            "fresh TypeScript SDK failed typecheck:\n{}{}",
            String::from_utf8_lossy(&ts_output.stdout),
            String::from_utf8_lossy(&ts_output.stderr)
        );
        let dist_entrypoint = world_dir.join("sdk-ts/dist/index.js");
        assert!(
            dist_entrypoint.is_file(),
            "TypeScript build must emit the publishable entrypoint"
        );
        let import_output = std::process::Command::new("node")
            .args([
                "--input-type=module",
                "--eval",
                "const sdk = await import(process.argv[1]); const input = { tick: 99n, player_id: 42, world_id: 7n, visible_snapshot: new Uint8Array([1, 2, 3]), world_config_view: { config_hash: new Uint8Array(32).fill(7), payload: new Uint8Array([4, 5]) }, fuel_budget_hints: { fuel_remaining: 12345n, host_calls_remaining: 77, output_bytes_remaining: 262144 }, message_inbox_cursor: { next_message_id: 555n } }; const inputBytes = sdk.encodeTickInput(input); const decodedInput = sdk.decodeTickInput(inputBytes); if (!decodedInput.ok || decodedInput.value.tick !== 99n) throw new Error('TickInput codec binding failed'); const resultBytes = sdk.encodeTickResult({ commands: [], messages: [] }); const decodedResult = sdk.decodeTickResult(resultBytes); if (!decodedResult.ok || decodedResult.value.commands.length !== 0) throw new Error('TickResult codec binding failed');",
                dist_entrypoint.to_str().unwrap(),
            ])
            .output()
            .unwrap();
        assert!(
            import_output.status.success(),
            "fresh TypeScript SDK dist entrypoint failed to import:\n{}{}",
            String::from_utf8_lossy(&import_output.stdout),
            String::from_utf8_lossy(&import_output.stderr)
        );

        let rust_output = std::process::Command::new("cargo")
            .args([
                "check",
                "--manifest-path",
                world_dir.join("sdk-rust/Cargo.toml").to_str().unwrap(),
            ])
            .output()
            .unwrap();
        assert!(
            rust_output.status.success(),
            "fresh Rust SDK failed cargo check:\n{}{}",
            String::from_utf8_lossy(&rust_output.stdout),
            String::from_utf8_lossy(&rust_output.stderr)
        );
    }
}
