//! SDK code generation from IDL.
//!
//! Generates TypeScript and Rust SDK code from an IdlDoc.
//! For TypeScript, custom actions are expanded as concrete action types
//! (方案β). For Rust, custom actions are generated as helper constructors
//! on CommandAction (the Rust equivalent of concrete types).

use crate::idl::{EnumDefs, IdlDoc, ModCustomAction};

// ── TypeScript generation ───────────────────────────────────────────

pub fn generate_typescript(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&ts_header(idl));
    out.push_str("\n");
    out.push_str(&ts_primitive_types());
    out.push_str("\n");
    out.push_str(&ts_enums(&idl.core.enums));
    out.push_str("\n");
    out.push_str(&ts_structure_types(idl));
    out.push_str("\n");
    out.push_str(&ts_core_actions(idl));
    out.push_str("\n");
    out.push_str(&ts_custom_actions(&idl.mods.custom_actions));
    out.push_str("\n");
    out.push_str(&ts_action_union(idl));
    out.push_str("\n");
    out.push_str(&ts_command_factories(idl));
    out.push_str("\n");
    out.push_str(&ts_constants(idl));
    out
}

fn ts_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn ts_primitive_types() -> String {
    r#"
export type UInt32 = number;
export type UInt64 = number | bigint;
export type PlayerId = UInt32;
export type RoomId = UInt32;
export type ObjectId = UInt64;
export type Tick = UInt64;
export type ResourceName = string;
export type ResourceAmount = UInt32;
export type ResourceCost = Record<ResourceName, ResourceAmount>;

export interface Position {
  x: number;
  y: number;
  room: RoomId;
}
"#
    .to_string()
}

fn ts_enums(enums: &EnumDefs) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("export type Direction = ");
    for (i, v) in enums.direction.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // BodyPart
    out.push_str("export type BodyPart = ");
    for (i, v) in enums.body_part.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // DamageType
    out.push_str("export type DamageType = ");
    for (i, v) in enums.damage_type.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n\n");

    // RejectionReason
    out.push_str("export type RejectionReasonCode = ");
    for (i, v) in enums.rejection_reason.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        if i % 8 == 0 && i > 0 {
            out.push_str("\n  | ");
        }
        out.push_str(&format!("\"{v}\""));
    }
    out.push_str(";\n");

    out
}

fn ts_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::from("export type StructureType = ");
    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();
    for (i, s) in all.iter().enumerate() {
        if i > 0 {
            out.push_str("\n  | ");
        }
        out.push_str(&format!("\"{s}\""));
    }
    out.push_str(";\n");
    out
}

fn ts_core_actions(idl: &IdlDoc) -> String {
    let mut out = String::new();

    for cmd in &idl.core.commands {
        out.push_str(&format!(
            "export interface {name}Action {{\n",
            name = cmd.name
        ));
        out.push_str(&format!("  type: \"{name}\";\n", name = cmd.name));
        for (field, ftype) in &cmd.fields {
            let ts_type = idl_to_ts_type(ftype);
            out.push_str(&format!("  {field}: {ts_type};\n"));
        }
        out.push_str("}\n\n");
    }

    out
}

fn idl_to_ts_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "ObjectId".into(),
        "Direction" => "Direction".into(),
        "ResourceName" | "ResourceName?" => "ResourceName".into(),
        "ResourceAmount" => "ResourceAmount".into(),
        "u32" => "number".into(),
        "u64" => "number".into(),
        "i32" => "number".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "BodyPart[]".into(),
        other => {
            if let Some(base) = other.strip_suffix('?') {
                format!("{}", idl_to_ts_type(base)) // optional fields just omit the ?
            } else {
                format!("unknown /* {other} */")
            }
        }
    }
}

fn ts_custom_actions(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom actions (from world.toml mods) ──\n\n");

    for action in actions {
        out.push_str(&format!(
            "export interface {name}Action {{\n  type: \"{name}\";\n  object_id: ObjectId;\n  target_id: ObjectId;\n",
            name = action.name,
        ));
        // Optional fields based on action config
        if action.damage_type.is_some() {
            out.push_str("  damage_type?: DamageType;\n");
        }
        if action.cooldown.is_some() {
            out.push_str("  cooldown?: number;\n");
        }
        out.push_str("}\n\n");
    }

    out
}

fn ts_action_union(idl: &IdlDoc) -> String {
    let mut out = String::from("export type Action = ");

    let mut first = true;
    for cmd in &idl.core.commands {
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = cmd.name));
    }
    for action in &idl.mods.custom_actions {
        if !first {
            out.push_str("\n  | ");
        }
        first = false;
        out.push_str(&format!("{name}Action", name = action.name));
    }
    out.push_str(";\n\n");

    out
}

fn ts_command_factories(idl: &IdlDoc) -> String {
    let mut out = String::from(
        "export interface CommandIntent<A extends Action = Action> {\n  sequence: UInt32;\n  action: A;\n}\n\n",
    );
    // ---- addCost helper ----
    out.push_str(
        "export function addCost(target: ResourceCost, source: ResourceCost): ResourceCost {\n  for (const [res, amt] of Object.entries(source)) {\n    target[res] = (target[res] ?? 0) + amt;\n  }\n  return target;\n}\n\n",
    );
    // ---- command factory ----

    out.push_str("export function command<A extends Action>(sequence: number, action: A): CommandIntent<A> {\n");
    out.push_str("  return { sequence, action };\n");
    out.push_str("}\n\n");

    out.push_str("export const actions = Object.freeze({\n");

    // Core command factories
    for cmd in &idl.core.commands {
        let fn_name = to_camel_case(&cmd.name);
        let args: Vec<String> = cmd
            .fields
            .iter()
            .map(|(f, t)| {
                let ts_type = idl_to_ts_type(t);
                let optional = t.ends_with('?');
                if optional {
                    format!("{f}?: {ts_type}")
                } else {
                    format!("{f}: {ts_type}")
                }
            })
            .collect();

        // Spawn uses rename="Spawn" on wire
        let wire_type = if cmd.name == "Spawn" {
            "Spawn"
        } else {
            &cmd.name
        };

        out.push_str(&format!(
            "  {fn_name}: ({args}) => ({{ type: \"{wire_type}\"",
            args = args.join(", ")
        ));
        for (field, _) in &cmd.fields {
            out.push_str(&format!(", {field}"));
        }
        out.push_str(" }) as const,\n");
    }

    // Custom action factories (方案β: concrete typed factories)
    for action in &idl.mods.custom_actions {
        let fn_name = to_camel_case(&action.name);
        out.push_str(&format!(
            "  {fn_name}: (object_id: ObjectId, target_id: ObjectId) =>\n    ({{ type: \"{name}\", object_id, target_id }}) as const,\n",
            fn_name = fn_name,
            name = action.name,
        ));
    }

    out.push_str("});\n\n");

    // body_energy_cost helper
    out.push_str(&format!(
        "export const BODY_PART_COST = Object.freeze({{\n{}}}\n) as const;\n\n",
        idl.core
            .body_part_costs
            .iter()
            .map(|(k, v)| format!("  {k}: {{ Energy: {v} }}"))
            .collect::<Vec<_>>()
            .join(",\n")
    ));

    out.push_str(
        r#"export function bodyCost(body: BodyPart[]): ResourceCost {
  const total: ResourceCost = {};
  for (const part of body) {
    const cost = BODY_PART_COST[part] ?? {};
    for (const [res, amt] of Object.entries(cost)) {
      total[res] = (total[res] ?? 0) + amt;
    }
  }
  return total;
}
"#,
    );

    out
}

fn ts_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("\n// ── Constants ──\n\n");
    out.push_str(&format!(
        "export const SDK_VERSION = \"{}\";\n",
        idl.engine_version
    ));
    out.push_str(&format!(
        "export const IDL_VERSION = \"{}\";\n",
        idl.idl_version
    ));
    out.push_str("export const ABI_VERSION = 1;\n\n");
    // AI game data markers (used by tick protocol)
    out.push_str("export const AI_GAME_DATA_START = \"___AI_GAME_DATA_START___\";\n");
    out.push_str("export const AI_GAME_DATA_END = \"___AI_GAME_DATA_END___\";\n\n");

    for (name, value) in &idl.core.constants {
        let js_val = match value {
            serde_json::Value::Number(n) => n.to_string(),
            serde_json::Value::Bool(b) => b.to_string(),
            _ => format!("{value}"),
        };
        out.push_str(&format!("export const {name} = {js_val};\n"));
    }

    out
}

fn to_camel_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if i == 0 {
            result.push(c.to_lowercase().next().unwrap_or(c));
        } else {
            result.push(c);
        }
    }
    result
}

// ── Rust generation ─────────────────────────────────────────────────

pub fn generate_rust(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str(&rust_header(idl));
    out.push_str("\n");
    // Type aliases live in types_template.rs; only enums + commands generated here.
    out.push_str(&rust_enums(idl));
    out.push_str("\n");
    out.push_str(&rust_structure_types(idl));
    out.push_str("\n");
    out.push_str(&rust_command_action(idl));
    out.push_str("\n");
    out.push_str(&rust_command_struct());
    out.push_str("\n");
    out.push_str(&rust_custom_constructors(&idl.mods.custom_actions));
    out.push_str("\n");
    out.push_str(&rust_constants(idl));
    out
}

fn rust_header(idl: &IdlDoc) -> String {
    format!(
        "// @generated by swarm-engine idl v{idl_version}\n\
         // world hash: {world_hash}\n\
         // engine version: {engine_version}\n\
         // DO NOT EDIT — this file is auto-generated.\n\n\
         use serde::{{Deserialize, Serialize}};\n",
        idl_version = idl.idl_version,
        world_hash = idl.world_hash,
        engine_version = idl.engine_version,
    )
}

fn rust_enums(idl: &IdlDoc) -> String {
    let mut out = String::new();

    // Direction
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum Direction {\n");
    for v in &idl.core.enums.direction {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");
    out.push_str(
        "impl Direction {\n    pub const fn offset(self) -> (i32, i32) {\n        match self {\n",
    );
    for v in &idl.core.enums.direction {
        let (dx, dy) = direction_offset(v);
        out.push_str(&format!("            Direction::{v} => ({dx}, {dy}),\n"));
    }
    out.push_str("        }\n    }\n}\n\n");

    // BodyPart
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum BodyPart {\n");
    for v in &idl.core.enums.body_part {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n\n");

    // DamageType
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n");
    out.push_str("pub enum DamageType {\n");
    for v in &idl.core.enums.damage_type {
        out.push_str(&format!("    {v},\n"));
    }
    out.push_str("}\n");

    out
}

fn direction_offset(v: &str) -> (i32, i32) {
    match v {
        "Top" => (0, -1),
        "TopRight" => (1, -1),
        "BottomRight" => (1, 0),
        "Bottom" => (0, 1),
        "BottomLeft" => (-1, 1),
        "TopLeft" => (-1, 0),
        _ => (0, 0),
    }
}

fn rust_structure_types(idl: &IdlDoc) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    out.push_str("pub struct StructureType(pub &'static str);\n\n");
    out.push_str("impl StructureType {\n");

    let all: Vec<&str> = idl
        .core
        .structure_types
        .iter()
        .chain(idl.mods.structure_types.iter().map(|s| &s.name))
        .map(|s| s.as_str())
        .collect();

    for s in &all {
        let const_name = s.to_uppercase().replace('-', "_");
        out.push_str(&format!(
            "    pub const {const_name}: Self = Self(\"{s}\");\n"
        ));
    }

    out.push_str("\n    pub fn new(name: impl Into<String>) -> Self {\n");
    out.push_str("        Self(Box::leak(name.into().into_boxed_str()))\n");
    out.push_str("    }\n\n");
    out.push_str("    pub fn as_str(self) -> &'static str { self.0 }\n");

    // Add PascalCase aliases (backward compat)
    for s in &all {
        if s.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
            out.push_str(&format!(
                "    #[allow(non_upper_case_globals)]\n    pub const {s}: Self = Self::{};\n",
                s.to_uppercase().replace('-', "_")
            ));
        }
    }
    out.push_str("}\n\n");

    // Custom Serialize / Deserialize (same pattern as engine's StructureType)
    out.push_str("impl Serialize for StructureType {\n");
    out.push_str(
        "    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {\n",
    );
    out.push_str("        s.serialize_str(self.0)\n    }\n}\n\n");
    out.push_str("impl<'de> Deserialize<'de> for StructureType {\n");
    out.push_str(
        "    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {\n",
    );
    out.push_str("        String::deserialize(d).map(Self::new)\n    }\n}\n\n");
    out.push_str("impl std::fmt::Display for StructureType {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        f.write_str(self.0)\n    }\n}\n\n");
    out.push_str("impl Default for StructureType {\n");
    out.push_str("    fn default() -> Self { Self::SPAWN }\n}\n");

    out
}

fn rust_command_action(idl: &IdlDoc) -> String {
    let mut out = String::new();

    out.push_str("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n");
    out.push_str("#[serde(tag = \"type\")]\n");
    out.push_str("pub enum CommandAction {\n");

    for cmd in &idl.core.commands {
        let variant_name = &cmd.name;
        if cmd.fields.is_empty() {
            out.push_str(&format!("    {variant_name},\n"));
        } else {
            out.push_str(&format!("    {variant_name} {{\n"));
            for (field, ftype) in &cmd.fields {
                let rust_type = idl_to_rust_type(ftype);
                out.push_str(&format!("        {field}: {rust_type},\n"));
            }
            out.push_str("    },\n");
        }
    }

    out.push_str("}\n");
    out
}

fn idl_to_rust_type(idl_type: &str) -> String {
    match idl_type {
        "ObjectId" => "u64".into(),
        "ObjectId?" => "Option<u64>".into(),
        "Direction" => "Direction".into(),
        "ResourceName" => "String".into(),
        "ResourceName?" => "Option<String>".into(),
        "ResourceAmount" => "u32".into(),
        "u32" => "u32".into(),
        "u64" => "u64".into(),
        "i32" => "i32".into(),
        "StructureType" => "StructureType".into(),
        "BodyPart[]" => "Vec<BodyPart>".into(),
        "String" => "String".into(),
        "JsonValue" => "serde_json::Value".into(),
        other => format!("String /* {other} */"),
    }
}

fn rust_command_struct() -> String {
    r#"
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct Command {
    pub sequence: u32,
    pub action: CommandAction,
}
"#
    .to_string()
}

fn rust_custom_constructors(actions: &[ModCustomAction]) -> String {
    if actions.is_empty() {
        return String::new();
    }

    let mut out = String::from("// ── Custom action constructors (方案β: typed helpers) ──\n\n");
    out.push_str("impl CommandAction {\n");

    for action in actions {
        let fn_name = action.name.to_lowercase();
        out.push_str(&format!(
            "    /// {description}\n    pub fn {fn_name}(object_id: ObjectId, target_id: ObjectId) -> Self {{\n        CommandAction::Action {{\n            action_type: \"{name}\".into(),\n            object_id,\n            target_id: Some(target_id),\n            payload: serde_json::Value::Object(serde_json::Map::new()),\n        }}\n    }}\n\n",
            description = action.description,
            name = action.name,
            fn_name = fn_name,
        ));
    }

    out.push_str("}\n");
    out
}

fn rust_constants(idl: &IdlDoc) -> String {
    let mut out = String::from("// ── Constants ──\n\n");

    for (name, value) in &idl.core.constants {
        match value {
            serde_json::Value::Number(n) => {
                if let Some(i) = n.as_u64() {
                    out.push_str(&format!("pub const {name}: u64 = {i};\n"));
                } else if let Some(f) = n.as_f64() {
                    out.push_str(&format!("pub const {name}: f64 = {f};\n"));
                }
            }
            _ => {}
        }
    }

    // Body part energy costs
    out.push_str("\npub const BODY_PART_COST: &[(BodyPart, u32)] = &[\n");
    for (name, cost) in &idl.core.body_part_costs {
        out.push_str(&format!("    (BodyPart::{name}, {cost}),\n"));
    }
    out.push_str("];\n\n");

    out.push_str(
        r#"pub fn body_energy_cost(body: &[BodyPart]) -> u32 {
    body.iter()
        .filter_map(|part| {
            BODY_PART_COST
                .iter()
                .find(|(p, _)| p == part)
                .map(|(_, cost)| *cost)
        })
        .sum()
}
"#,
    );

    out
}

// ── SDK cache path helpers ──────────────────────────────────────────

/// Compute the cache directory for a given world hash.
pub fn sdk_cache_dir(world_hash: &str) -> std::path::PathBuf {
    std::path::PathBuf::from("/data/swarm/sdk-cache").join(world_hash)
}

/// Return the engine source dir path.
fn engine_dir() -> Result<std::path::PathBuf, String> {
    let exe = std::env::current_exe().map_err(|e| format!("current_exe: {e}"))?;
    // Walk up from the binary to find the engine src/ directory
    for ancestor in exe.ancestors().take(10) {
        let path = ancestor.join("sdk-templates");
        if path.is_dir() {
            return Ok(path.to_path_buf());
        }
    }
    // Fallback: check relative to CWD
    let cwd_templates = std::env::current_dir()
        .unwrap_or_default()
        .join("sdk-templates");
    if cwd_templates.is_dir() {
        return Ok(cwd_templates);
    }
    Err("Cannot locate engine sdk-templates directory".into())
}

/// Copy all template files from engine/sdk-templates/<lang>/ into the output SDK directory.
fn merge_sdk_templates(lang: &str, out_dir: &std::path::Path) -> Result<(), String> {
    let templates_dir = engine_dir()?.join(lang);
    if !templates_dir.is_dir() {
        return Err(format!(
            "sdk-templates/{lang} not found at {}",
            templates_dir.display()
        ));
    }
    copy_dir(&templates_dir, out_dir).map_err(|e| format!("copy sdk-templates/{lang}: {e}"))?;
    Ok(())
}

/// Recursive directory copy. Overwrites existing files.
fn copy_dir(src: &std::path::Path, dst: &std::path::Path) -> Result<(), String> {
    std::fs::create_dir_all(dst).map_err(|e| format!("mkdir {}: {e}", dst.display()))?;
    for entry in std::fs::read_dir(src).map_err(|e| format!("readdir {}: {e}", src.display()))? {
        let entry = entry.map_err(|e| format!("entry: {e}"))?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir(&src_path, &dst_path)?;
        } else {
            std::fs::copy(&src_path, &dst_path).map_err(|e| {
                format!("copy {} -> {}: {e}", src_path.display(), dst_path.display())
            })?;
        }
    }
    Ok(())
}

pub fn sha256_hex(data: &[u8]) -> String {
    use sha2::{Digest, Sha256};
    let mut hasher = Sha256::new();
    hasher.update(data);
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

// ── CLI entry points ────────────────────────────────────────────────

use crate::world::WorldConfig;

/// CLI: dump IDL to stdout as JSON.
pub fn cli_dump_idl(world_toml_path: &str) -> Result<String, String> {
    let config = WorldConfig::from_world_toml(world_toml_path)
        .map_err(|e| format!("load world.toml: {e}"))?;
    let toml_bytes =
        std::fs::read(world_toml_path).map_err(|e| format!("read {world_toml_path}: {e}"))?;
    let world_hash = sha256_hex(&toml_bytes);

    let body_parts = crate::components::BodyPartRegistry::from_defs(config.body_part_types);
    let structures = crate::components::StructureTypeRegistry::default();
    let special_effects =
        crate::components::SpecialEffectRegistry::from_defs(config.special_effects);
    let custom_actions = crate::components::CustomActionRegistry::from_defs(config.custom_actions);

    let idl = crate::idl::extract_idl(
        &world_hash,
        &body_parts,
        &structures,
        &special_effects,
        &custom_actions,
    );

    serde_json::to_string_pretty(&idl).map_err(|e| format!("serialize IDL: {e}"))
}

/// CLI: generate SDK files to output directory.
pub fn cli_generate_sdk(world_toml_path: &str, out_base: &str) -> Result<(), String> {
    let idl_json = cli_dump_idl(world_toml_path)?;
    let idl: crate::idl::IdlDoc =
        serde_json::from_str(&idl_json).map_err(|e| format!("parse IDL: {e}"))?;

    let out_dir = std::path::PathBuf::from(out_base).join(&idl.world_hash);
    std::fs::create_dir_all(&out_dir).map_err(|e| format!("create {}: {e}", out_dir.display()))?;

    // Merge templates with generated code for TypeScript
    let ts_code = generate_typescript(&idl);
    let ts_sdk_dir = out_dir.join("sdk-ts");
    merge_sdk_templates("ts", &ts_sdk_dir)?;
    let ts_src = ts_sdk_dir.join("src");
    std::fs::create_dir_all(&ts_src).map_err(|e| format!("create {}: {e}", ts_src.display()))?;
    std::fs::write(ts_src.join("commands.ts"), ts_code)
        .map_err(|e| format!("write sdk-ts/commands.ts: {e}"))?;

    // Merge templates with generated code for Rust
    let rust_code = generate_rust(&idl);
    let rust_sdk_dir = out_dir.join("sdk-rust");
    merge_sdk_templates("rust", &rust_sdk_dir)?;
    let rust_src = rust_sdk_dir.join("src");
    std::fs::create_dir_all(&rust_src)
        .map_err(|e| format!("create {}: {e}", rust_src.display()))?;
    std::fs::write(rust_src.join("commands.rs"), rust_code)
        .map_err(|e| format!("write sdk-rust/commands.rs: {e}"))?;

    // Write IDL itself
    std::fs::write(out_dir.join("idl.json"), idl_json)
        .map_err(|e| format!("write idl.json: {e}"))?;

    // Write metadata
    let meta = serde_json::json!({
        "world_hash": idl.world_hash,
        "engine_version": idl.engine_version,
        "idl_version": idl.idl_version,
        "generated_at": chrono_now(),
    });
    std::fs::write(
        out_dir.join("meta.json"),
        serde_json::to_string_pretty(&meta).unwrap(),
    )
    .map_err(|e| format!("write meta.json: {e}"))?;

    Ok(())
}

fn chrono_now() -> String {
    // Simple UTC timestamp without chrono dependency
    use std::time::SystemTime;
    match SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
        Ok(d) => format!("{}", d.as_secs()),
        Err(_) => "unknown".into(),
    }
}
